"""
PRODUCT DEFINITIONS for C9400 Macallan Linecards

The product definition file contains descriptive data about a "family" or set of UUTs for the purposes of test automation.
This file should be atomic to the product family defined by Cisco marketing for release (i.e. DO NOT mix product familiy releases).

Convention:
For embedded dict keys
1. All upper case = flash/cookie/eeprom parameters (Note: CMPD data should be used for the latest revision data and per Area data if available and/or applicable.)
2. All lower case = internal script parameters

Structure:
  family = {
      'COMMON': {...}
      '<PRODUCT_A>': {...}
      '<PRODUCT_B>': {...}
      ...
      '<PRODUCT_N>': {...}
  } # family_end

  Note1: Product "codenames" MUST be used as the '<PRODUCT_X>' names in the family structure.
         This is done to discern the difference between any cost reduced or improved products having the same
         PIDs as it's previous generation (both codename and CPN should be unique).

  WARNING: All dict elements in this structure must be of numeric, str, tuple, list, or dict types.
           Do not use complex elements (e.g. named tuples, imported objects, etc.),
           as this will cause malformed string input for some processing of the ast function.
"""

__title__ = "C9400 Macallan Linecards Product Definitions"
__version__ = '0.1.1'
__family__ = "macallan_linecard"

family = {
    'COMMON': {
        'product_family': 'macallan_linecard',

        # Product Generation: only GEN3 supported.
        'product_generation': 'GEN3',

        # UUT Categories: 'SWITCH', 'UPLINK_MODULE', 'ADAPTER_MODULE', 'CABLE', 'SUP', 'LINECARD'
        'uut_category': 'LINECARD',

        'modular': True,

        # Flash Params
        'TERMINAL_LINES': '0',

        # Images
        'btldr': {'image': '',  # pre-packaged in linux kernel
                  'rev': {'ver': '', 'date': ''}},
        'linux': {'image': 'mcln_x86_kernel_20171101.SSA',
                  'rev': ''},
        'diag': {'image': 'sdX86_thr1B.180228',
                 'rev': ''},
        'fpga': {'image': '',  # pre-packaged in linux kernel
                 'rev': '',
                 'name': ''},
        'ios_dirs': {'local': '', 'remote': ''},
        'ios_test_pid': 'STEST2',
        'ios_supp_files': {},

        # Identity Protection types: QUACK2, ACT2
        'identity_protection_type': 'ACT2',
        # Sequence to program all IdPro, valid types: QUACK, ACT, X509-n (n=1 to total_hashes)
        'idpro_sequence': ['ACT'],

        # Disk enumeration specifies the rank of all attached disks.  Primary is mandatory and is the target disk for all images (diags & IOS).
        'disk_enums': {'primary': 'sda', 'secondary': None, 'tertiary': None},
        # Flash Device is the directory mapped location of the primary parent mounted device as seen by the bootloader. Relative dir is from the mount point.
        'flash_device': {'name': 'flash', 'relative_dir': 'user', 'device_num': 3},
        # Disk Enumerated Device Mounts must have an ordered precedence for dependent mount locations.
        # Parent mounts are placed first in the list.  Specified mounts should correspond to enumerated disks.
        # Format is a list of tuples: [(<device number>, <mount point>), ...]
        'device_mounts': {
            'primary': [(3, '/mnt/flash3'), (1, '/mnt/flash1'), (2, '/mnt/flash2'),
                        (4, '/mnt/flash4'), (5, '/mnt/flash5'), (6, '/mnt/flash6'), (7, '/mnt/flash7')],
            'secondary': None,
            'tertiary': None,
        },
        # Partition definition for each device type.  Populated AFTER the OS determines the device size.
        'partitions': {
            'primary': None,
            'secondary': None,
            'tertiary': None,
        },

        # Fan tests
        'fan': {
            'status_value': '0x0000002A',
            'regs': {'fan1': '0x3C', 'fan2': '0x44', 'fan3': '0x4C'},
            'speed_settings': {'LOW': '0x0A', 'HIGH': '0xFF', 'NOMINAL': '0x7B'},
        },
        # RTC tests
        'rtc': {'time_zone': 'GMT'},

        # StackRac tests
        'stackrac': {'datastack': 1},

        # SerDesEye
        'serdeseye': {'interfaces': ['SIF', 'NIF']},

        # SBC params
        'sbc': {'enabled': True, 'temperature_reg': 'READ_TEMPERATURE_2'},

        # Sysinit messages required for passing.
        # Format: list of tuples form of [(<regex message pattern>, <total number of msgs>), (<regex message pattern2>, <total number of msgs>), ...]
        'sysinit_required_to_pass': [('PCIE[0234]: \(RC\) X4 GEN-2 link UP', 4)],  # From Passport need "\"
        # See PRODUCT sections.

        # Chamber Corners (N-Corners)
        #  Format = [('<chamber corner temp+voltage>', adt_enabled), ...]
        #  The temp+voltage designations are 2+2letters:
        #    HT = High Temp,  LT = Low Temp,  HV = High Voltage, LV = Low Voltage, Nx = Nominal/Ambient
        'chamber_corners': [('LTHV', True), ('HTLV', True)],

        # Power cycling test (PCBP2C)
        'max_power_cycles': 4,

        # Product Sequence Definition Settings
        # (Parameters that are passed to the sequence definition build-out.)
        'prod_seq_def': {
            'PCBP2C': {},
            'PCB2C': {},
            'PCBPM': {},
            'PCBFT': {'total_loop_time_secs': 3600},
        },

        # Diag Tests within the Stardust testlist
        # For product-specific tests, place them in the product sections for appending.
        'diag_tests': [('CraySRAMTest',    {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('DopRegs',         {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopMem',          {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 800}),
                       ('DopIntr',         {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PortFrames',      {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('JumboFrames',     {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopMACsecDiag',   {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('DebugFrames',     {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopEEE',          {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopOciPortTest',  {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopPtpFlexTimer', {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopPtpIngTest',   {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopPtpEgrTest',   {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('PortIntrDiag',    {'areas': ['PCB2C'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PortCableDiag',   {'areas': ['PCB2C'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('PortPtpIngTest',  {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('PortPtpEgrTest',  {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopPSRO',         {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('CrayCorePSRO',    {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopMBIST',        {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopCiscoPRBS',    {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ],

        'traffic_cases_library': {
            '24S': {
                # GRANT24
                # External ------------------------------------------------------
                'TrafCase_EXT_10_64': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-24': {'speed': '10', 'size': 64, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_100_512': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-24': {'speed': '100', 'size': 512, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_1G_1518': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-24': {'speed': '1000', 'size': 1518, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_auto_9198': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-24': {'speed': 'auto', 'size': 9198, 'macsec_mode': 'macsec', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                # Internal -------------------------------------------------------
                'TrafCase_PHY_10_64': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-24': {'speed': '10', 'size': 64, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_100_512': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-24': {'speed': '100', 'size': 512, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_1G_1518': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-24': {'speed': '1000', 'size': 1518, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_auto_9198': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-24': {'speed': 'auto', 'size': 9198, 'macsec_mode': 'macsec', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                'TrafCase_PHY_auto_64': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-24': {'speed': 'auto', 'size': 64, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_auto_1518': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-24': {'speed': 'auto', 'size': 1518, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                }
            },
            '24XS': {
                # HAIG24
                # External ------------------------------------------------------
                'TrafCase_EXT_10_64': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-24': {'speed': '10', 'size': 64, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_100_512': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-24': {'speed': '100', 'size': 512, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_1G_1518': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-24': {'speed': '1000', 'size': 1518, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_auto_9198': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-24': {'speed': 'auto', 'size': 9198, 'macsec_mode': 'macsec', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                # Internal -------------------------------------------------------
                'TrafCase_PHY_10_64': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-24': {'speed': '10', 'size': 64, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_100_512': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-24': {'speed': '100', 'size': 512, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_1G_1518': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-24': {'speed': '1000', 'size': 1518, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_auto_9198': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-24': {'speed': 'auto', 'size': 9198, 'macsec_mode': 'macsec', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                'TrafCase_PHY_auto_64': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-24': {'speed': 'auto', 'size': 64, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_auto_1518': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-24': {'speed': 'auto', 'size': 1518, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                }
            },
            '48': {
                # External ------------------------------------------------------
                'TrafCase_EXT_10_64': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-48': {'speed': '10', 'size': 64}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_10_1518': {
                    'enabled': False,
                    'areas': ['PCBPM'],
                    'downlink_ports': {'1-48': {'speed': '10', 'size': 1518}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                'TrafCase_EXT_100_512': {
                    'enabled': False,
                    'areas': ['PCBP2C', 'PCBPM'],
                    'downlink_ports': {'1-48': {'speed': '100', 'size': 512}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_100_1518': {
                    'enabled': False,
                    'areas': ['PCBP2C', 'PCBPM'],
                    'downlink_ports': {'1-48': {'speed': '100', 'size': 1518}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                'TrafCase_EXT_1G_1518': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-48': {'speed': '1000', 'size': 1518}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_1G_64': {
                    'enabled': False,
                    'areas': ['PCBPM'],
                    'downlink_ports': {'1-48': {'speed': '1000', 'size': 64}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_1G_9198': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-48': {'speed': '1000', 'size': 9198}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                'TrafCase_EXT_auto_9198': {
                    'enabled': False,
                    'areas': ['PCBPM'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 9198}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': True,
                    'macsec_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                # Internal -------------------------------------------------------
                'TrafCase_PHY_10_64': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '10', 'size': 64}},
                    'sup_ports': {'1-8': {'speed': '1G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                'TrafCase_PHY_100_512': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '100', 'size': 512}},
                    'sup_ports': {'1-8': {'speed': '1G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                'TrafCase_PHY_1G_1518': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '1000', 'size': 1518}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                'TrafCase_PHY_auto_9198': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 9198}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                'TrafCase_PHY_auto2_9198': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 9198}},
                    'sup_ports': {'9-10': {'speed': '40G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

            },
            '48P': {
                # BELL-LITE
                # External ------------------------------------------------------
                'TrafCase_EXT_10_64': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-48': {'speed': '10', 'size': 64, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_100_512': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-48': {'speed': '100', 'size': 512, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_1G_1518': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-48': {'speed': '1000', 'size': 1518, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_auto_9198': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 9198, 'macsec_mode': 'macsec', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                # Internal -------------------------------------------------------
                'TrafCase_PHY_10_64': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '10', 'size': 64, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_100_512': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '100', 'size': 512, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_1G_1518': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '1000', 'size': 1518, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_auto_9198': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 9198, 'macsec_mode': 'macsec', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                'TrafCase_PHY_auto_64': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 64, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_auto_1518': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 1518, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                }
            },
            '48S': {
                # GRANT48
                # External ------------------------------------------------------
                'TrafCase_EXT_10_64': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-48': {'speed': '10', 'size': 64, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_100_512': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-48': {'speed': '100', 'size': 512, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_1G_1518': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-48': {'speed': '1000', 'size': 1518, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_auto_9198': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 9198, 'macsec_mode': 'macsec', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                # Internal -------------------------------------------------------
                'TrafCase_PHY_10_64': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '10', 'size': 64, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_100_512': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '100', 'size': 512, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_1G_1518': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '1000', 'size': 1518, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_auto_9198': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 9198, 'macsec_mode': 'macsec', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                'TrafCase_PHY_auto_64': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 64, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_auto_1518': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 1518, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                }
            },
            '48T': {
                # DIMPLE
                # External ------------------------------------------------------
                'TrafCase_EXT_10_64': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-48': {'speed': '10', 'size': 64, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_100_512': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-48': {'speed': '100', 'size': 512, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_1G_1518': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-48': {'speed': '1000', 'size': 1518, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_auto_9198': {
                    'enabled': False,
                    'areas': ['PCBP2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 9198, 'macsec_mode': 'macsec', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                # Internal -------------------------------------------------------
                'TrafCase_PHY_10_64': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '10', 'size': 64, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_100_512': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '100', 'size': 512, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_1G_1518': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '1000', 'size': 1518, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_auto_9198': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 9198, 'macsec_mode': 'macsec', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                'TrafCase_PHY_auto_64': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 64, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_auto_1518': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 1518, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                }
            },
            '48U': {
                # BELL and BOWMORE(temporary)
                # External ------------------------------------------------------
                'TrafCase_EXT_10_64': {
                    'enabled': False,
                    'areas': ['PCBP2C', 'PCBPM'],
                    'downlink_ports': {'1-48': {'speed': '10', 'size': 64, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_100_512': {
                    'enabled': False,
                    'areas': ['PCBP2C', 'PCBPM'],
                    'downlink_ports': {'1-48': {'speed': '100', 'size': 512, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_1G_1518': {
                    'enabled': False,
                    'areas': ['PCBP2C', 'PCBPM'],
                    'downlink_ports': {'1-48': {'speed': '1000', 'size': 1518, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_auto_9198': {
                    'enabled': False,
                    'areas': ['PCBP2C', 'PCBPM'],
                    'downlink_ports': {
                        '1-48': {'speed': 'auto', 'size': 9198, 'macsec_mode': 'macsec', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                # Internal -------------------------------------------------------
                'TrafCase_PHY_10_64': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '10', 'size': 64, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_100_512': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '100', 'size': 512, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_1G_1518': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '1000', 'size': 1518, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_auto_9198': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {
                        '1-48': {'speed': 'auto', 'size': 9198, 'macsec_mode': 'macsec', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                'TrafCase_PHY_auto_64': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 64, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_auto_1518': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 1518, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                }
            },
            '48UX': {
                # VAT69 and VAT69CR
                # External ------------------------------------------------------
                'TrafCase_EXT_10_64': {
                    'enabled': False,
                    'areas': ['PCBP2C', 'PCBPM'],
                    'downlink_ports': {'1-48': {'speed': '10', 'size': 64, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_100_512': {
                    'enabled': False,
                    'areas': ['PCBP2C', 'PCBPM'],
                    'downlink_ports': {'1-48': {'speed': '100', 'size': 512, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_1G_1518': {
                    'enabled': False,
                    'areas': ['PCBP2C', 'PCBPM'],
                    'downlink_ports': {'1-48': {'speed': '1000', 'size': 1518, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_auto_9198': {
                    'enabled': False,
                    'areas': ['PCBP2C', 'PCBPM'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 9198, 'macsec_mode': 'macsec', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_2_5G_128': {
                    'enabled': False,
                    'areas': ['PCBP2C', 'PCBPM'],
                    'downlink_ports': {'1-48': {'speed': '2.5G', 'size': 128, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_5G_512': {
                    'enabled': False,
                    'areas': ['PCBP2C', 'PCBPM'],
                    'downlink_ports': {'1-48': {'speed': '5G', 'size': 512, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_10G_9198': {
                    'enabled': False,
                    'areas': ['PCBP2C', 'PCBPM'],
                    'downlink_ports': {'1-48': {'speed': '10G', 'size': 9198, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                # Internal -------------------------------------------------------
                'TrafCase_PHY_10_64': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '10', 'size': 64, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_100_512': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '100', 'size': 512, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_1G_1518': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '1000', 'size': 1518, 'duplex': 'full', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_auto_9198': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {
                        '1-48': {'speed': 'auto', 'size': 9198, 'macsec_mode': 'macsec', 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'macsec_enabled': True,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_2.5G_128': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '2.5G', 'size': 128, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_5G_512': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '5G', 'size': 512, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_10G_9198': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': '10G', 'size': 9198, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

                'TrafCase_PHY_auto_64': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 64, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_auto_1518': {
                    'enabled': True,
                    'areas': ['PCB2C'],
                    'downlink_ports': {'1-48': {'speed': 'auto', 'size': 1518, 'stress': True}},
                    'sup_ports': {'1-8': {'speed': '10G', 'loopback_direction': 'Forward', 'loopback_point': 'MAC0'}},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 30,
                    'pretraf_cmds': [], 'traf_cmds': [],
                }
            },
        },  # traffic_cases

        'cmpd_type_verify_manifest': {
            'S.All.1': {'areas': ['PCBP2C'],
                        'types': [
                            # Put CMPD Item field names here,
                            # Ensure the order matches the CMPD db entries!
                                  ],
                        },
        },  # cmpd



    },

    'BELL': {
        'cfg_pids': [],
        'MODEL_NUM': 'C9400-LC-48U',
        'MODEL_REVISION_NUM': 'A0',
        'TAN_NUM': '68-5593-07',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-16884-07',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'POE1_SERIAL_NUM': '',
        'POE1_ASSEMBLY_NUM': '73-16439-02',
        'POE1_REVISION_NUM': 'A0',
        'POE2_SERIAL_NUM': '',
        'POE2_ASSEMBLY_NUM': '73-16439-02',
        'POE2_REVISION_NUM': 'A0',
        'VERSION_ID': 'V01',
        'SBC_CFG': '',
        'MAC_BLOCK_SIZE': '48',
        'poe': {'uut_ports': '1-48', 'type': 'UPOE', 'volt_range': (47.0, 56.0), 'current_range': (1008, 1232)},
        'diag_tests': [('PortFrames',      {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('PortIntrDiag',    {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PortCableDiag',   {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('PoeDetTest',      {'areas': ['PCBPM'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test'}),
                       ('PoeClassTest',    {'areas': ['PCBPM'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test'}),
                       ('PoePowerTest',    {'areas': ['PCBPM'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_power_test'})
                       ],
        'traffic_cases': ('traffic_cases_library', '48U'),
        'cmpd_types': ('cmpd_type_verify_manifest', []),
        'eco_manifest': {
        },
    },

    'DIMPLE': {
        'cfg_pids': [],
        'MODEL_NUM': 'C9400-LC-48T',
        'MODEL_REVISION_NUM': 'A0',
        'TAN_NUM': '68-5155-07',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-16002-07',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'VERSION_ID': 'V01',
        'SBC_CFG': '',
        'MAC_BLOCK_SIZE': '48',
        'diag_tests': [('JumboFrames',     {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('PortIntrDiag',    {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PortCableDiag',   {'areas': ['PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000})
            ],
        'traffic_cases': ('traffic_cases_library', '48T'),
        'cmpd_types': ('cmpd_type_verify_manifest', []),
        'eco_manifest': {
        },
    },

    'VAT69': {
        'cfg_pids': [],
        'MODEL_NUM': 'C9400-LC-48UX',
        'MODEL_REVISION_NUM': 'A0',
        'TAN_NUM': '68-5156-07',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-16003-07',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'POE1_SERIAL_NUM': '',
        'POE1_ASSEMBLY_NUM': '73-16438-02',
        'POE1_REVISION_NUM': 'A0',
        'POE2_SERIAL_NUM': '',
        'POE2_ASSEMBLY_NUM': '73-16438-02',
        'POE2_REVISION_NUM': 'A0',
        'VERSION_ID': 'V01',
        'SBC_CFG': '',
        'MAC_BLOCK_SIZE': '48',
        'poe': {'uut_ports': '1-48', 'type': 'UPOE', 'volt_range': (47.0, 56.0), 'current_range': (1008, 1232)},
        'diag_tests': [('PoeDetTest',      {'areas': ['PCBPM'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test'}),
                       ('PoeClassTest',    {'areas': ['PCBPM'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test'}),
                       ('PoePowerTest',    {'areas': ['PCBPM'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_power_test'})
                       ],
        'traffic_cases': ('traffic_cases_library', '48UX'),
        'cmpd_types': ('cmpd_type_verify_manifest', []),
        'eco_manifest': {
        },
    },

    'VAT69CR': {
        'cfg_pids': [],
        'MODEL_NUM': 'C9400-LC-48UX',
        'MODEL_REVISION_NUM': 'A0',
        'TAN_NUM': '68-6664-01',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-19200-01',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'POE1_SERIAL_NUM': '',
        'POE1_ASSEMBLY_NUM': '73-16123-02',
        'POE1_REVISION_NUM': 'A0',
        'POE2_SERIAL_NUM': '',
        'POE2_ASSEMBLY_NUM': '73-16123-02',
        'POE2_REVISION_NUM': 'A0',
        'VERSION_ID': 'V01',
        'SBC_CFG': '',
        'MAC_BLOCK_SIZE': '48',
        'poe': {'uut_ports': '1-48', 'type': 'UPOE', 'volt_range': (47.0, 56.0), 'current_range': (1008, 1232)},
        'diag_tests': [('CraySRAMTest',    {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('DopRegs',         {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopMem',          {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 800}),
                       ('DopIntr',         {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PortFrames',      {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('JumboFrames',     {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopMACsecDiag',   {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('DebugFrames',     {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopEEE',          {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopOciPortTest',  {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopPtpFlexTimer', {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopPtpIngTest',   {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopPtpEgrTest',   {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('PortIntrDiag',    {'areas': ['PCBP2C', 'PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PortCableDiag',   {'areas': ['PCBP2C', 'PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('PortPtpIngTest',  {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('PortPtpEgrTest',  {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopPSRO',         {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('CrayCorePSRO',    {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopMBIST',        {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopCiscoPRBS',    {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PoeDetTest',      {'areas': ['PCBPM'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test'}),
                       ('PoeClassTest',    {'areas': ['PCBPM'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test'}),
                       ('PoePowerTest',    {'areas': ['PCBPM'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_power_test'})
            ],
        'traffic_cases': ('traffic_cases_library', '48UX'),
        'cmpd_types': ('cmpd_type_verify_manifest', []),
        'eco_manifest': {},
    },

    'HAIG': {
        'cfg_pids': [],
        'MODEL_NUM': 'C9400-LC-24XS',
        'MODEL_REVISION_NUM': 'A0',
        'TAN_NUM': '68-5158-05',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-16008-05',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'VERSION_ID': 'V01',
        'SBC_CFG': '',
        'MAC_BLOCK_SIZE': '24',
        'diag_tests': [('PortFrames',      {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopMBIST',        {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400})
            ],
        'traffic_cases': ('traffic_cases_library', '24XS'),
        'cmpd_types': ('cmpd_type_verify_manifest', ['S.All.1']),
        'eco_manifest': {
            ('73-16008-05A0', 'ALL'): ('D999999', '90272', ['ALL'], ''),
            ('73-16008-05B0', 'ALL'): ('D999999', '90492', ['ALL'], ''),
            ('73-16008-0506', 'ALL'): ('D999999', '85595', ['ALL'], ''),
            ('73-16008-0507', 'ALL'): ('87306', '87305', ['ALL'], ''),
            ('73-16008-0507', 'ALL'): ('D999999', '87039', ['ALL'], ''),
            ('73-16008-05A0', 'ALL'): ('96697', '96694', ['ALL'], ''),
            ('73-16008-05A0', 'ALL'): ('D999999', '90272', ['ALL'], ''),
            ('73-16008-05B0', 'ALL'): ('D999999', '90492', ['ALL'], ''),
            ('73-16008-0506', 'ALL'): ('D999999', '85595', ['ALL'], ''),
            ('73-16008-0507', 'ALL'): ('87306', '87305', ['ALL'], ''),
            ('73-16008-0507', 'ALL'): ('D999999', '87039', ['ALL'], ''),
            ('73-16008-05A0', 'ALL'): ('96697', '96694', ['ALL'], ''),
            ('73-16008-05A0', 'ALL'): ('D999999', '90272', ['ALL'], ''),
            ('73-16008-05B0', 'ALL'): ('D999999', '90492', ['ALL'], ''),
            ('73-16008-0506', 'ALL'): ('D999999', '85595', ['ALL'], ''),
            ('73-16008-0507', 'ALL'): ('87306', '87305', ['ALL'], ''),
        },
    },

    'BELL-LITE': {
        'cfg_pids': [],
        'MODEL_NUM': 'C9400-LC-48P',
        'MODEL_REVISION_NUM': 'A0',
        'TAN_NUM': '68-5594-01',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-16885-06',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'POE1_SERIAL_NUM': '',
        'POE1_ASSEMBLY_NUM': '73-16439-02',
        'POE1_REVISION_NUM': 'A0',
        'POE2_SERIAL_NUM': '',
        'POE2_ASSEMBLY_NUM': '73-16439-02',
        'POE2_REVISION_NUM': 'A0',
        'VERSION_ID': 'V01',
        'SBC_CFG': '',
        'MAC_BLOCK_SIZE': '48',
        'poe': {'uut_ports': '1-48', 'type': 'POE+', 'volt_range': (47.0, 56.0), 'current_range': (500, 700)},
        'diag_tests': [('CraySRAMTest',    {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('DopRegs',         {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopMem',          {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 800}),
                       ('DopIntr',         {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PortFrames',      {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('JumboFrames',     {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopMACsecDiag',   {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('DebugFrames',     {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopEEE',          {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopOciPortTest',  {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopPtpFlexTimer', {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopPtpIngTest',   {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopPtpEgrTest',   {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('PortIntrDiag',    {'areas': ['PCBP2C', 'PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PortCableDiag',   {'areas': ['PCBP2C', 'PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('PortPtpIngTest',  {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('PortPtpEgrTest',  {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopPSRO',         {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('CrayCorePSRO',    {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopMBIST',        {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopCiscoPRBS',    {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PoeDetTest',      {'areas': ['PCBPM'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test'}),
                       ('PoeClassTest',    {'areas': ['PCBPM'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test'}),
                       ('PoePowerTest',    {'areas': ['PCBPM'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_power_test'}),
                       ('PoeFaultTest',    {'areas': ['PCBPM'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200})
                       ],
        'traffic_cases': ('traffic_cases_library', '48P'),
        'cmpd_types': ('cmpd_type_verify_manifest', []),
        'eco_manifest': {
            # UPoE
            ('73-16885-0606', 'ALL'): ('D999999', '85598', ['ALL'], ''),
            ('73-16001-0606', 'ALL'): ('D999999', '85597', ['ALL'], ''),
            ('73-16001-0705', 'ALL'): ('D999999', '89950', ['ALL'], ''),
            ('73-16885-0705', 'ALL'): ('D999999', '90003', ['ALL'], ''),
            ('73-16885-08A0', 'ALL'): ('D999999', '94513', ['ALL'], ''),
            ('73-16885-0803', 'ALL'): ('D999999', '91664', ['ALL'], ''),
            ('73-16885-0606', 'ALL'): ('D999999', '85598', ['ALL'], ''),
            ('73-16001-0606', 'ALL'): ('D999999', '85597', ['ALL'], ''),
            ('73-16001-0705', 'ALL'): ('D999999', '89950', ['ALL'], ''),
            ('73-16885-0705', 'ALL'): ('D999999', '90003', ['ALL'], ''),
            ('73-16885-08A0', 'ALL'): ('D999999', '94513', ['ALL'], ''),
            ('73-16885-0803', 'ALL'): ('D999999', '91664', ['ALL'], ''),
            ('73-16885-0606', 'ALL'): ('D999999', '85598', ['ALL'], ''),
            ('73-16001-0606', 'ALL'): ('D999999', '85597', ['ALL'], ''),
            ('73-16001-0705', 'ALL'): ('D999999', '89950', ['ALL'], ''),
            ('73-16885-0705', 'ALL'): ('D999999', '90003', ['ALL'], ''),
            ('73-16885-08A0', 'ALL'): ('D999999', '94513', ['ALL'], ''),
            ('73-16885-0803', 'ALL'): ('D999999', '91664', ['ALL'], ''),
            # Others
        },
    },

    'GRANT24': {
        'cfg_pids': [],
        'MODEL_NUM': 'C9400-LC-24S',
        'MODEL_REVISION_NUM': 'A0',
        'TAN_NUM': '68-5157-01',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-16007-01',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'VERSION_ID': 'V01',
        'SBC_CFG': '',
        'MAC_BLOCK_SIZE': '24',
        'diag_tests': [('CraySRAMTest',    {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('DopRegs',         {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopMem',          {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 800}),
                       ('DopIntr',         {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PortFrames',      {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('JumboFrames',     {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopMACsecDiag',   {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('DebugFrames',     {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopEEE',          {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopOciPortTest',  {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopPtpFlexTimer', {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopPtpIngTest',   {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopPtpEgrTest',   {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('PortIntrDiag',    {'areas': ['PCBP2C', 'PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PortCableDiag',   {'areas': ['PCBP2C', 'PCB2C'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('PortPtpIngTest',  {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('PortPtpEgrTest',  {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopPSRO',         {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('CrayCorePSRO',    {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopMBIST',        {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopCiscoPRBS',    {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400})
                      ],
        'traffic_cases': ('traffic_cases_library', '24S'),
        'cmpd_types': ('cmpd_type_verify_manifest', []),
        'eco_manifest': {
        },
    },

    'GRANT48': {
        'cfg_pids': [],
        'MODEL_NUM': 'C9400-LC-48S',
        'MODEL_REVISION_NUM': 'A0',
        'TAN_NUM': '68-6331-01',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-18668-01',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'VERSION_ID': 'V01',
        'SBC_CFG': '',
        'MAC_BLOCK_SIZE': '48',
        'diag_tests': [('CraySRAMTest',    {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('DopRegs',         {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopMem',          {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 800}),
                       ('DopIntr',         {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PortFrames',      {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('JumboFrames',     {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopMACsecDiag',   {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('DebugFrames',     {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopEEE',          {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopOciPortTest',  {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopPtpFlexTimer', {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopPtpIngTest',   {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopPtpEgrTest',   {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('PortIntrDiag',    {'areas': ['PCBP2C', 'PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PortCableDiag',   {'areas': ['PCBP2C', 'PCB2C'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('PortPtpIngTest',  {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('PortPtpEgrTest',  {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopPSRO',         {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('CrayCorePSRO',    {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopMBIST',        {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopCiscoPRBS',    {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400})
                      ],
        'traffic_cases': ('traffic_cases_library', '48S'),
        'cmpd_types': ('cmpd_type_verify_manifest', []),
        'eco_manifest': {
        },
    },

    'BOWMORE': {
        'cfg_pids': [],
        'MODEL_NUM': 'BOWMORE',
        'MODEL_REVISION_NUM': 'A0',
        'TAN_NUM': '68-6660-01',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-19156-01',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'POE1_SERIAL_NUM': '',
        'POE1_ASSEMBLY_NUM': '73-19180-02',
        'POE1_REVISION_NUM': 'A0',
        'POE2_SERIAL_NUM': '',
        'POE2_ASSEMBLY_NUM': '73-19180-02',
        'POE2_REVISION_NUM': 'A0',
        'VERSION_ID': 'V01',
        'SBC_CFG': '',
        'MAC_BLOCK_SIZE': '48',
        'poe': {'uut_ports': '1-48', 'type': 'UPOE', 'volt_range': (47.0, 56.0), 'current_range': (1008, 1232)},
        'diag_tests': [('CraySRAMTest',    {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('DopRegs',         {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopMem',          {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 800}),
                       ('DopIntr',         {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PortFrames',      {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('JumboFrames',     {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopMACsecDiag',   {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('DebugFrames',     {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopEEE',          {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopOciPortTest',  {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopPtpFlexTimer', {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopPtpIngTest',   {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopPtpEgrTest',   {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('PortIntrDiag',    {'areas': ['PCBP2C', 'PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PortCableDiag',   {'areas': ['PCBP2C', 'PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('PortPtpIngTest',  {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('PortPtpEgrTest',  {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopPSRO',         {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('CrayCorePSRO',    {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopMBIST',        {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('DopCiscoPRBS',    {'areas': ['PCBP2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 400}),
                       ('PoeDetTest',      {'areas': ['PCBPM'], 'enabled': False, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test'}),
                       ('PoeClassTest',    {'areas': ['PCBPM'], 'enabled': False, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test'}),
                       ('PoePowerTest',    {'areas': ['PCBPM'], 'enabled': False, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_power_test'})
                      ],
        'traffic_cases': ('traffic_cases_library', '48U'),
        'cmpd_types': ('cmpd_type_verify_manifest', []),
        'eco_manifest': {},
    }

}  # family_end
