"""
PRODUCT DEFINITIONS for C3K NewtonCSR

The product definition file contains descriptive data about a "family" or set of UUTs for the purposes of test automation.
This file should be atomic to the product family defined by Cisco marketing for release (i.e. DO NOT mix product familiy releases).

Convention:
For embedded dict keys
1. All upper case = flash/cookie/eeprom parameters (Note: CMPD data should be used for the latest revision data and per Area data if available and/or applicable.)
2. All lower case = internal script parameters

Structure:
  family = {
      'COMMON': {...}
      '<PRODUCT_A>': {...}
      '<PRODUCT_B>': {...}
      ...
      '<PRODUCT_N>': {...}
  } # family_end
  Note1: Product "codenames" MUST be used as the '<PRODUCT_X>' names in the family structure.
         This is done to discern the difference between any cost reduced or improved products having the same
         PIDs as it's previous generation (both codename and CPN should be unique).

  WARNING: All dict elements in this structure must be of numeric, str, tuple, list, or dict types.
           Do not use complex elements (e.g. named tuples, imported objects, etc.),
           as this will cause malformed string input for some processing of the ast function.
"""

__title__ = "C3K NewtonCSR Product Definitions"
__version__ = '0.2.1'
__family__ = "edison"
__consumer__ = 'c3850.Edison'


family = {
    'COMMON': {
        'product_family': "edison",

        # Product Generation: 'GEN1', 'GEN2', 'GEN3'
        'product_generation': 'GEN2',

        # UUT Categories: 'SWITCH', 'UPLINK_MODULE', 'ADAPTER_MODULE', 'CABLE'
        'uut_category': 'SWITCH',

        # Test Area process flow
        'process_flow': ['ICT', 'PCBDL', 'PCBST', 'PCB2C', 'ASSY', 'SYSBI', 'HIPOT', 'SYSFT'],

        # Flash Params
        'DDR_SPEED': '667',
        'LINUX_COREMASK': '15',
        'STKPWR_SERIAL_NUM': '',
        'STKPWR_ASSEMBLY_NUM': '',
        'STKPWR_REVISION_NUM': '',
        'USB_SERIAL_NUM': '',
        'USB_ASSEMBLY_NUM': '',
        'USB_REVISION_NUM': '',
        'TERMINAL_LINES': '0',
        'MAC_BLOCK_SIZE': '128',

        # Images
        'btldr': {'image': 'polaris_c3850_20160310.SPA.prod',
                  'rev': {'ver': '3.58', 'date': 'Mar 10 2016'}},
        'linux': {'image': 'vmlinux_idcs_3.10.mzip.SSA',  # 'vmlinux2015Apr22.mzip.SSA',
                  'rev': ''},
        'diag': {'image': 'stardust_ecsr_th_011516',  # 'stardustThrCSR.2015Sep11',
                 'rev': ''},
        'fpga': {'image': 'morse_csr_02_06_20140922_PP_relkey_hmac.hex',
                 'rev': '0206',
                 'name': 'bell'},
        # MCU images given by a subdir as the dict keys.
        'mcu': {'images': {'kirch88': ['app_data.srec_V88', 'app_flash.bin_V88', 'kirchhoff_swap.bin', 'Cisco_loader.srec',
                                       'c_kirchhoff_swap_33.bin', 'coulomb_kirchhoff_33.bin']},
                'name': 'alchemy',
                'rev': {'ios': 'APPL 0.88 (0x58)  41 (0x29)  16 (0x10)', 'coulomb': 'APPL 0.33 (0x21)  41 (0x29)  0 (0x00)'}},
        'ios_dirs': {'local': '', 'remote': 'NG3K_IOS'},
        'ios_test_pid': 'S3850UK9-37E',
        'ios_supp_files': {8: [('S3850UK9-32-0SE', 'SR_pkgs'), ('S3850UK9-33SE', 'SR_pkgs')],
                           9: [('ACTUAL', 'recovery')]},

        # settings before IOS main image installation
        'ios_pre_install_params': {'ASIC_PCI_RESET': '1', 'EI_NOPROG': '1'},
        # IOS clean up items
        'ios_cleanup_items': ['obfl', 'crashinfo', 'startup-config'],
        # Rommon params to keep
        'rommon_params_to_keep': ['ASIC_PCI_RESET', 'BOOT_LOADER_UPGRADE_DISABLE' 'SWITCH_NUMBER', 'BOOT', 'BAUD',
                                  'CFG_MODEL_NUM', 'RECOVERY_BUNDLE', 'TERMLINES', 'SBC_CFG', 'MANUAL_BOOT'],
        # default license files/dirs
        'default_license_files': {1: ['tracelogs'],
                                  5: ['dyn_eval', 'eval', 'persist', 'pri', 'red', '*d_license*.*'],
                                  6: ['dyn_eval', 'eval', 'persist', 'pri', 'red', '*d_license*.*']},

        # Identity Protection types: QUACK2, ACT2
        'identity_protection_type': 'QUACK2',  # 'QUACK2',
        # Sequence to program all IdPro, valid types: QUACK, ACT, X509-n (n=1 to total_hashes)
        'idpro_sequence': ['X509-1', 'QUACK', 'X509-2'],
        # Access Point SUDI params
        'x509_sudi_hash': ['SHA1', 'SHA256'],
        'x509_sudi_request_type': 'PROD',
        'x509_sudi_cert_method': 'KEY',
        'hidden_device': '/dev/sda5',

        # ASIC
        'asic': {'type_ids': ['0x3ce']},

        # Disk enumeration specifies the rank of all attached disks.  Primary is mandatory and is the target disk for all images (diags & IOS).
        'disk_enums': {'primary': 'sda', 'secondary': None, 'tertiary': None},
        # Flash Device is the directory mapped location of the primary parent mounted device as seen by the bootloader. Relative dir is from the mount point.
        'flash_device': {'name': 'flash', 'relative_dir': 'user', 'device_num': 3},
        # Disk Enumerated Device Mounts must have an ordered precedence for dependent mount locations.
        # Parent mounts are placed first in the list.  Specified mounts should correspond to enumerated disks.
        # Format is a list of tuples: [(<device number>, <mount point>), ...]
        'device_mounts': {
            'primary': [(3, '/mnt'), (1, '/mnt/sd1'), (5, '/mnt/sd5'), (6, '/mnt/sd6'), (7, '/mnt/sd7'), (8, '/mnt/sd8'), (9, '/mnt/sd9')],
            'secondary': None,
            'tertiary': None,
        },
        # Partition definition for each device type.  Populated AFTER the OS determines the device size.
        'partitions': {
            'primary': None,
            'secondary': None,
            'tertiary': None,
        },

        # Passive RFID Tag
        # 'rfid': {'chassis_enabled': True},

        # Fan tests
        'fan': {
            'status_value': '0x0000002A',
            'regs': {'fan1': '0x3C', 'fan2': '0x44', 'fan3': '0x4C'},
            'speed_settings': {'LOW': '0x0A', 'HIGH': '0xFF', 'NOMINAL': '0x7B'},
        },
        # RTC tests
        'rtc': {'time_zone': 'GMT'},

        # StackRac tests
        'stackrac': {'datastack': 1},

        # SerDesEye
        'serdeseye': {'interfaces': ['SIF', 'NIF']},

        # I2C
        'i2c': {
            'target_device_instances': {
                'PCBST': [1, 2, 3],
                'PCB2C': [1, 2, 3],
                'ASSY': [1],
                'PCBFT': [2, 3],
                'SYSBI': [2, 3]
            },
            'tests': ['SCCTestNonDestructive']
        },

        # SBC params
        'sbc': {'enabled': True, 'temperature_reg': 'READ_TEMPERATURE_2'},

        # PSU
        'psu': {'slots': ['A', 'B']},

        # Configuration check
        'cnf_psu_keys': {'uut_type': ['PID'], 'sn': ['SN']},
        'cnf_pcamap_keys': {'uut_type': ['pid'], 'sn': ['sn']},

        # TST recording
        'pcamap_to_tst_keymap': {'pid': 'uut_type', 'vid': 'version_id', 'sn': 'serial_number', 'hwv': 'tan_hw_rev',
                                 'vpn': 'tan', 'eci': 'eci'},
        'psu_to_tst_keymap': {'PID': 'uut_type', 'SN': 'serial_number', 'TAN': 'tan', 'TAN Rev': 'tan_hw_rev',
                              'VID': 'version_id', 'CLEI': 'clei'},
        'pcamap_items_for_tst': ['1', '2'],

        # Sysinit messages required for passing.
        # Format: list of tuples form of [(<regex message pattern>, <total number of msgs>), (<regex message pattern2>, <total number of msgs>), ...]
        # 'sysinit_required_to_pass': [('Doppler [0-1] PCIe link lane width is 4', 2)],
        # See PRODUCT sections.

        # Chamber Corners (N-Corners)
        #  Format = [('<chamber corner temp+voltage>', adt_enabled), ...]
        #  The temp+voltage designations are 2+2letters:
        #    HT = High Temp,  LT = Low Temp,  HV = High Voltage, LV = Low Voltage, Nx = Nominal/Ambient
        'chamber_corners': [('LTHV', True), ('HTLV', True)],

        # Power cycling test (FST)
        'max_power_cycles': 4,

        # Product Sequence Definition Settings
        # (Parameters that are passed to the sequence definition build-out.)
        'prod_seq_def': {
            'PCBST': {},
            'PCB2C': {},
            'ASSY': {},
            'PCBFT': {'total_loop_time_secs':  3000, 'idpro_periphs': False},
            'SYSBI': {'total_loop_time_secs':  3000, 'idpro_periphs': False},
        },

        # Voltage Margin Table for Level Check
        #  Format is {'<voltage rail name>': {...values...}, ...}
        #         or {'<voltage rail name>': {'bins': {<bin# 0-x>: {...values...}, ...}}, ...}
        #  Values: trim     = Trim voltage level from nominal.
        #          vnom     = Nominal Voltage rating.
        #          mhi, mlo = Margin Percentage for high and low independently.
        #          gb       = Guard Band Percentage (+/-).
        'vmargin_table': {
            '3.3V':                   {'trim': 0, 'vnom': 3.3,   'mhi': 0.05, 'mlo': 0.05, 'gb': 0.027},
            '2.5V':                   {'trim': 0, 'vnom': 2.5,   'mhi': 0.05, 'mlo': 0.05, 'gb': 0.027},
            '1.8V':                   {'trim': 0, 'vnom': 1.8,   'mhi': 0.05, 'mlo': 0.05, 'gb': 0.027},
            '1.5V':                   {'trim': 0, 'vnom': 1.5,   'mhi': 0.05, 'mlo': 0.05, 'gb': 0.027},
            '1.2V':                   {'trim': 0, 'vnom': 1.2,   'mhi': 0.03, 'mlo': 0.03, 'gb': 0.027},
            '1.0V':                   {'trim': 0, 'vnom': 1.0,   'mhi': 0.03, 'mlo': 0.03, 'gb': 0.027},
            '0.9V':                   {'trim': 0, 'vnom': 0.9,   'mhi': 0.05, 'mlo': 0.05, 'gb': 0.027},
            'DP-vdd_1.05V':           {'trim': 0, 'vnom': 1.05,  'mhi': 0.03, 'mlo': 0.03, 'gb': 0.027},
            'DP-vdd_1.085V':          {'trim': 0, 'vnom': 1.085, 'mhi': 0.03, 'mlo': 0.03, 'gb': 0.027},
            'DP-ser_1.0V':            {'trim': 0, 'vnom': 1.0,   'mhi': 0.03, 'mlo': 0.03, 'gb': 0.027},
            'DP-pll_1.8V':            {'trim': 0, 'vnom': 1.8,   'mhi': 0.03, 'mlo': 0.03, 'gb': 0.027},
            # '0.98V-DP0': {'bins': {0: {'trim': 0, 'vnom': 0.98, 'mhi': 0.03, 'mlo': 0.03, 'gb': 0.015},
            #                        1: {'trim': 0, 'vnom': 0.98, 'mhi': 0.03, 'mlo': 0.03, 'gb': 0.015}}},
            # '1.5V-DOP':  {'bins': {0: {'trim': 0, 'vnom': 1.5,  'mhi': 0.03, 'mlo': 0.03, 'gb': 0.015},
            #                        1: {'trim': 0, 'vnom': 1.5,  'mhi': 0.03, 'mlo': 0.03, 'gb': 0.015}}},
        },

        # Temperature Table
        # Table MUST account for 1) Test Area, 2) Environmental temperature, and 3) Operational State of UUT.
        # Format is {'<index name>': {'<testarea>': {'<environ temp>': {'idle': xx, 'traf': xx, 'diag': xx, 'gb': xx}, ...}, ...}, ...}
        # 'idle' = State of UUT powered on but not doing much.
        # 'traf' = State of UUT running full bandwidth traffic
        # 'diag' = State of UUT running diagnostic tests (might have to average over serveral tests)
        # 'gb'   = Guard Band +/-% for pass or fail; 0.20 = +/-20% of the selected limit value above.
        'temperature_table': {
            'Exhaust':   {'PCB2C': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 35, 'gb': 0.35},
                                    'HOT':     {'idle': 60,  'traf': 65, 'diag': 65, 'gb': 0.35},
                                    'COLD':    {'idle': 5,   'traf': 20, 'diag': 20, 'gb': 1.00}},
                          'PCBST': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 40, 'gb': 0.35}},
                          'PCBFT': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 40, 'gb': 0.35}},
                          'SYSBI': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 40, 'gb': 0.35}}},
            'Intake':    {'PCB2C': {'AMBIENT': {'idle': 28,  'traf': 28, 'diag': 28, 'gb': 0.35},
                                    'HOT':     {'idle': 60,  'traf': 65, 'diag': 65, 'gb': 0.35},
                                    'COLD':    {'idle': 2.5, 'traf': 10, 'diag': 10, 'gb': 1.00}},
                          'PCBST': {'AMBIENT': {'idle': 32,  'traf': 30, 'diag': 30, 'gb': 0.35}},
                          'PCBFT': {'AMBIENT': {'idle': 32,  'traf': 30, 'diag': 30, 'gb': 0.35}},
                          'SYSBI': {'AMBIENT': {'idle': 32,  'traf': 32, 'diag': 32, 'gb': 0.35}}},
            'Doppler_0': {'PCB2C': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35},
                                    'HOT':     {'idle': 70,  'traf': 80, 'diag': 80, 'gb': 0.35},
                                    'COLD':    {'idle': 10,  'traf': 30, 'diag': 30, 'gb': 1.00}},
                          'PCBST': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}},
                          'PCBFT': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}},
                          'SYSBI': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35, 'delta': 35}}},
        },

        # Diag Tests within the Stardust testlist
        # For product-specific tests, place them in the product sections for appending.
        'diag_tests': [('SysMem',          {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('SysRegs',         {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('RTCTest',         {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       # ('UsbDet',          {'areas': ['PCB2C'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       # ('UsbConsoleLB',    {'areas': ['PCB2C'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('DopRegs',         {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('DopMem',          {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('DopPSRO',         {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('DopMBIST',        {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('DopInterrupt',    {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('DopNifCiscoPRBS', {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('DopOffload',      {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('DopPtpFlexTimer', {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('DopPtpIngTest',   {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('DopPtpEgrTest',   {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('SupFrames',       {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('SupJumboFrames',  {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('PortFrames',      {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('JumboFrames',     {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('RcpFrames',       {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('DebugFrames',     {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('DopEEE',          {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('DopMACsecDiag',   {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('DopFssDiag',      {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('OOBM',            {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('DopSifCiscoPRBS', {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('InsideLoop',      {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('Cable',           {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('PowerDown',       {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('PortIntrDiag',    {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('REProtocol',      {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('REI2C',           {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('AlchemySystem',   {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('AlchemyCommands', {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('PsDet',           {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('StackPwrDet',     {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ('StackPwrCtrl',    {'areas': ['PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1200}),
                       ],

        'traffic_cases_library': {
            '24': {
                'TrafCase_NIF_1': {
                    'downlink_ports': {'1-24': {'speed': '1000'}},
                    'uplink_ports': {'25-26': {'speed': '1000'}, '27-28': {'speed': '10G'}}
                },
                'TrafCase_NIF_2': {
                    'downlink_ports': {'1-24': {'speed': '1000'}},
                    'uplink_ports': {'25-26': {'speed': '10G'}, '27-28': {'speed': '1000'}}
                },
                'TrafCase_EXT_1G_1518_a': {
                    'enabled': False,
                    'areas': ['DBGSYS', 'PCBST', 'ASSY'],
                    'downlink_ports': {
                        '1-24': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'uplink_ports': {
                        '25-26': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '27-28': {'speed': '10G', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': True,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_1G_1518_b': {
                    'enabled': False,
                    'areas': ['DBGSYS', 'PCBST', 'ASSY'],
                    'downlink_ports': {
                        '1-24': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'uplink_ports': {
                        '25-26': {'speed': '10G', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '27-28': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': True,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_1G_1518': {
                    'enabled': True,
                    'areas': ['ALL'],
                    'downlink_ports': {
                        '1-24': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'macsec'},
                    },
                    'uplink_ports': {
                        '25-26': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '27-28': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_1G_64': {
                    'enabled': True,
                    'areas': ['ALL'],
                    'downlink_ports': {
                        '1-24': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'macsec'},
                    },
                    'uplink_ports': {
                        '25-26': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '27-28': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_10M_64': {
                    'enabled': True,
                    'areas': ['DBGSYS', 'SYSBI', 'PCBFT'],
                    'downlink_ports': {
                        '1-24': {'speed': '10', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'macsec'},
                    },
                    'uplink_ports': {
                        '25-26': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True,
                                  'forwarding_schm': 'bridging',
                                  'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart',
                                  'macsec_mode': 'nomacsec'},
                        '27-28': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True,
                                  'forwarding_schm': 'bridging',
                                  'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart',
                                  'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_Auto_1024': {
                    'enabled': True,
                    'areas': ['DBGSYS', 'SYSBI', 'PCBFT'],
                    'downlink_ports': {
                        '1-24': {'speed': 'AUTO', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1024, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'macsec'},
                    },
                    'uplink_ports': {
                        '25-26': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1024, 'stress': True,
                                  'forwarding_schm': 'bridging',
                                  'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart',
                                  'macsec_mode': 'nomacsec'},
                        '27-28': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1024, 'stress': True,
                                  'forwarding_schm': 'bridging',
                                  'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart',
                                  'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

            },
            '48': {
                'TrafCase_NIF_1': {
                    'downlink_ports': {'1-48': {'speed': '1000'}},
                    'uplink_ports': {'49-50,53-54': {'speed': '1000'}, '51-52,55-56': {'speed': '10G'}}
                },
                'TrafCase_NIF_2': {
                    'downlink_ports': {'1-48': {'speed': '1000'}},
                    'uplink_ports': {'49-50,53-54': {'speed': '10G'}, '51-52,55-56': {'speed': '1000'}}
                },
                'TrafCase_EXT_1G_1518_a': {
                    'enabled': True,
                    'areas': ['DBGSYS', 'PCBST', 'ASSY'],
                    'downlink_ports': {
                        '1-48': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'uplink_ports': {
                        '49-50,53-54': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '51-52,55-56': {'speed': '10G', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': True,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_1G_1518_b': {
                    'enabled': True,
                    'areas': ['DBGSYS', 'PCBST', 'ASSY'],
                    'downlink_ports': {
                        '1-48': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'uplink_ports': {
                        '49-50,53-54': {'speed': '10G', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '51-52,55-56': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'poe_enabled': True,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_1G_1518': {
                    'enabled': True,
                    'areas': ['ALL'],
                    'downlink_ports': {
                        '1-48': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'macsec'},
                    },
                    'uplink_ports': {
                        '49-50,53-54': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '51-52,55-56': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_1G_64': {
                    'enabled': True,
                    'areas': ['ALL'],
                    'downlink_ports': {
                        '1-48': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'macsec'},
                    },
                    'uplink_ports': {
                        '49-50,53-54': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '51-52,55-56': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_10M_64': {
                    'enabled': True,
                    'areas': ['DBGSYS', 'SYSBI', 'PCBFT'],
                    'downlink_ports': {
                        '1-48': {'speed': '10', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'macsec'},
                    },
                    'uplink_ports': {
                        '49-50,53-54': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64,
                                        'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart',
                                        'macsec_mode': 'nomacsec'},
                        '51-52,55-56': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64,
                                        'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart',
                                        'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_Auto_1024': {
                    'enabled': True,
                    'areas': ['DBGSYS', 'SYSBI', 'PCBFT'],
                    'downlink_ports': {
                        '1-48': {'speed': 'AUTO', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1024, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart', 'macsec_mode': 'macsec'},
                    },
                    'uplink_ports': {
                        '49-50,53-54': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1024,
                                        'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart',
                                        'macsec_mode': 'nomacsec'},
                        '51-52,55-56': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1024,
                                        'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'fifo': 8, 'lifo': 1, 'frames_link': 'norestart',
                                        'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'poe_enabled': False,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

            },
        },  # traffic_cases

        'cmpd_type_verify_manifest': {
            'T.All.1': {'areas': ['PCBST', 'PCB2C'],
                        'types': ['MAC_ADDR', 'MANUAL_BOOT',
                                  'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                  'MODEL_NUM', 'MODEL_REVISION_NUM',
                                  'DDR_SPEED', 'TERMLINES'
                                  ],
                        },
            'T.All.2': {'areas': ['ASSY', 'SYSBI', 'PCBFT'],
                        'types': ['MAC_ADDR',
                                  'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                  'SYSTEM_SERIAL_NUM', 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                  'STKPWR_ASSEMBLY_NUM', 'STKPWR_REVISION_NUM', 'STKPWR_SERIAL_NUM',
                                  'USB_ASSEMBLY_NUM', 'USB_REVISION_NUM', 'USB_SERIAL_NUM',
                                  'TAN_NUM', 'TAN_REVISION_NUMBER',
                                  'VERSION_ID', 'DDR_SPEED',
                                  'CLEI_CODE_NUMBER', 'ECI_CODE_NUMBER',
                                  ],
                        },
            'T.All.3': {'areas': ['SYSFT'],
                        'types': ['MAC_ADDR',
                                  'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                  'SYSTEM_SERIAL_NUM', 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                  'STKPWR_ASSEMBLY_NUM', 'STKPWR_REVISION_NUM', 'STKPWR_SERIAL_NUM',
                                  'USB_ASSEMBLY_NUM', 'USB_REVISION_NUM', 'USB_SERIAL_NUM',
                                  'TAN_NUM', 'TAN_REVISION_NUMBER',
                                  'VERSION_ID', 'DDR_SPEED',
                                  'CLEI_CODE_NUMBER', 'ECI_CODE_NUMBER',
                                  ],
                        },

            'P.24.1': {'areas': ['PCBST', 'PCB2C'],
                       'types': ['MAC_ADDR', 'MANUAL_BOOT',
                                 'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                 # 'POE1_ASSEMBLY_NUM', 'POE1_REVISION_NUM', 'POE1_SERIAL_NUM',
                                 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                 'DDR_SPEED', 'TERMLINES'
                                 ],
                       },
            'P.24.2': {'areas': ['ASSY', 'SYSBI', 'PCBFT'],
                       'types': ['MAC_ADDR',
                                 'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                 # 'POE1_ASSEMBLY_NUM', 'POE1_REVISION_NUM', 'POE1_SERIAL_NUM',
                                 'SYSTEM_SERIAL_NUM', 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                 'STKPWR_ASSEMBLY_NUM', 'STKPWR_REVISION_NUM', 'STKPWR_SERIAL_NUM',
                                 'USB_ASSEMBLY_NUM', 'USB_REVISION_NUM', 'USB_SERIAL_NUM',
                                 'TAN_NUM', 'TAN_REVISION_NUMBER',
                                 'VERSION_ID', 'DDR_SPEED',
                                 'CLEI_CODE_NUMBER', 'ECI_CODE_NUMBER',
                                 ],
                       },
            'P.24.3': {'areas': ['SYSFT'],
                       'types': ['MAC_ADDR',
                                 'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                 'POE1_ASSEMBLY_NUM', 'POE1_REVISION_NUM', 'POE1_SERIAL_NUM',
                                 'SYSTEM_SERIAL_NUM', 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                 'STKPWR_ASSEMBLY_NUM', 'STKPWR_REVISION_NUM', 'STKPWR_SERIAL_NUM',
                                 'USB_ASSEMBLY_NUM', 'USB_REVISION_NUM', 'USB_SERIAL_NUM',
                                 'TAN_NUM', 'TAN_REVISION_NUMBER',
                                 'VERSION_ID', 'DDR_SPEED',
                                 'CLEI_CODE_NUMBER', 'ECI_CODE_NUMBER',
                                 ],
                       },
            'P.48.1': {'areas': ['PCBST', 'PCB2C'],
                       'types': ['MAC_ADDR', 'MANUAL_BOOT',
                                 'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                 # 'POE1_ASSEMBLY_NUM', 'POE1_REVISION_NUM', 'POE1_SERIAL_NUM',
                                 # 'POE2_ASSEMBLY_NUM', 'POE2_REVISION_NUM', 'POE2_SERIAL_NUM',
                                 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                 'DDR_SPEED', 'TERMLINES'
                                 ],
                       },
            'P.48.2': {'areas': ['ASSY', 'SYSBI', 'PCBFT'],
                       'types': ['MAC_ADDR',
                                 'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                 # 'POE1_ASSEMBLY_NUM', 'POE1_REVISION_NUM', 'POE1_SERIAL_NUM',
                                 # 'POE2_ASSEMBLY_NUM', 'POE2_REVISION_NUM', 'POE2_SERIAL_NUM',
                                 'SYSTEM_SERIAL_NUM', 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                 'STKPWR_ASSEMBLY_NUM', 'STKPWR_REVISION_NUM', 'STKPWR_SERIAL_NUM',
                                 'USB_ASSEMBLY_NUM', 'USB_REVISION_NUM', 'USB_SERIAL_NUM',
                                 'TAN_NUM', 'TAN_REVISION_NUMBER',
                                 'VERSION_ID', 'DDR_SPEED',
                                 'CLEI_CODE_NUMBER', 'ECI_CODE_NUMBER',
                                 ],
                       },
            'P.48.3': {'areas': ['SYSFT'],
                       'types': ['MAC_ADDR',
                                 'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                 'POE1_ASSEMBLY_NUM', 'POE1_REVISION_NUM', 'POE1_SERIAL_NUM',
                                 'POE2_ASSEMBLY_NUM', 'POE2_REVISION_NUM', 'POE2_SERIAL_NUM',
                                 'SYSTEM_SERIAL_NUM', 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                 'STKPWR_ASSEMBLY_NUM', 'STKPWR_REVISION_NUM', 'STKPWR_SERIAL_NUM',
                                 'USB_ASSEMBLY_NUM', 'USB_REVISION_NUM', 'USB_SERIAL_NUM',
                                 'TAN_NUM', 'TAN_REVISION_NUMBER',
                                 'VERSION_ID', 'DDR_SPEED',
                                 'CLEI_CODE_NUMBER', 'ECI_CODE_NUMBER',
                                 ],
                       },
        },  # cmpd

    },

    'NEWTONCSR24': {
        'cfg_pids': ['WS-C3850-24T-L', 'WS-C3850-24T-E', 'WS-C3850-24T-S'],
        'MODEL_NUM': 'WS-C3850-24T',
        'MODEL_REVISION_NUM': '',
        'TAN_NUM': '800-43074-03',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-16297-04',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'VERSION_ID': 'V01',
        'SBC_CFG':   '',
        'CLEI_CODE_NUMBER': '',
        'ECI_CODE_NUMBER': '',
        'sysinit_required_to_pass': [('Doppler 0 PCIe link lane width is 4', 1)],
        'asic': {'type_ids': ['0x3ce'], 'core_count': 1, 'locations': ['U98']},
        'traffic_cases': ('traffic_cases_library', '24'),
        'cmpd_types': ('cmpd_type_verify_manifest', ['T.All.1', 'T.All.2', 'T.All.3']),
        'eco_manifest': {('73-16297-0107', 'ALL'): ('E140213', '', ['PCBST', 'PCB2C'], 'P1B'),
                         ('73-16297-0203', 'ALL'): ('E060414', '', ['PCBST', 'PCB2C'], 'P2B'),
                         ('73-16297-05B0', 'ALL'): ('EA553365', '91577', ['PCBST', 'PCB2C'], ''),
                         ('73-16297-05A0', 'ALL'): ('EA536264', '76655', ['PCBST', 'PCB2C'], ''),
                         ('73-16297-04B0', 'ALL'): ('EA526167', '73511', ['PCBST', 'PCB2C'], ''),
                         ('73-16297-04A0', 'ALL'): ('EA523543', '67548', ['PCBST', 'PCB2C'], ''),
                         ('73-16297-0403', 'ALL'): ('E102414', '58259', ['PCBST', 'PCB2C'], ''),
                         # ('73-16297-05A0', 'ALL'): (None, '80242', ['SYSFT'], ''),
                         ('800-43074-03D0', 'ALL'): ('EA555228', '91561', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43074-03B0', 'ALL'): ('EA550394', '86994', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43074-02C0', 'ALL'): ('EA533983', '76232', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43074-02B0', 'ALL'): ('EA534723', '75664', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43074-02A0', 'ALL'): ('EA526167', '73513', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43074-01D0', 'ALL'): ('EA530824', '72996', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43074-01C0', 'ALL'): ('EA527875', '70379', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43074-01B0', 'ALL'): ('EA524874', '69476', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43074-01A0', 'ALL'): ('EA523543', '67550', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43074-0116', 'ALL'): ('E102414', '58261', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-43074-02B0', 'ALL'): (None, '92053', ['SYSFT'], ''),
                         ('800-43074-03D0', 'FTX'): (None, '91907', ['SYSFT'], ''),
                         ('800-43074-03A0', 'FTX'): (None, '87087', ['SYSFT'], ''),
                         # ('800-43074-03A0', 'FTX'): (None, '79516', ['SYSFT'], ''),
                         ('800-43074-02A0', 'FTX'): (None, '79508', ['SYSFT'], ''),
                         ('800-43074-01A0', 'FTX'): (None, '68812', ['SYSFT'], ''),
                         ('800-43074-01B0', 'FTX'): (None, '70235', ['SYSFT'], ''),
                         ('800-43074-01C0', 'FTX'): (None, '70608', ['SYSFT'], ''),
                         ('800-43074-01D0', 'FTX'): (None, '73250', ['SYSFT'], ''),
                         # ('800-43074-02A0', 'FTX'): (None, '74023', ['SYSFT'], ''),
                         ('800-43074-02B0', 'FTX'): (None, '75711', ['SYSFT'], ''),
                         # ('800-43074-02B0', 'FTX'): (None, '75712', ['SYSFT'], ''),
                         ('800-43074-02C0', 'FTX'): (None, '77227', ['SYSFT'], ''),
                         },
    },

    'NEWTONCSR24P': {
        'cfg_pids': ['WS-C3850-24P-L', 'WS-C3850-24P-E', 'WS-C3850-24P-S', 'WS-C3850-24PW-S'],
        'MODEL_NUM': 'WS-C3850-24P',
        'MODEL_REVISION_NUM': 'A0',
        'TAN_NUM': '800-43046-03',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-15805-04',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'POE1_SERIAL_NUM': '',
        'POE1_ASSEMBLY_NUM': '73-16123-03',
        'POE1_REVISION_NUM': 'A0',
        'VERSION_ID': 'V01',
        'SBC_CFG':   '',
        'CLEI_CODE_NUMBER': '',
        'ECI_CODE_NUMBER': '',
        'sysinit_required_to_pass': [('Doppler 0 PCIe link lane width is 4', 1)],
        'asic': {'type_ids': ['0x3ce'], 'core_count': 1, 'locations': ['U98']},
        'poe': {'uut_ports': '1-24', 'type': 'POE+', 'volt_range': (47.0, 56.0), 'current_range': (486, 594), 'icutcode': 34},
        'diag_tests': [('PoeDetTest_CSCO',   {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [1], 'mdimode': [0, 1]}}),
                       ('PoeDetTest_IEEE',   {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [2], 'mdimode': [1]}}),
                       ('PoeClassTest_0',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [0]}}),
                       ('PoeClassTest_1',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [1]}}),
                       ('PoeClassTest_2',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [2]}}),
                       ('PoeClassTest_3',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [3]}}),
                       ('PoeClassTest_4',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [4]}}),
                       ('PoePowerTest',      {'cmd': 'PoePowerTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_power_test'}),
                       ],
        'traffic_cases': ('traffic_cases_library', '24'),
        'cmpd_types': ('cmpd_type_verify_manifest', ['P.24.1', 'P.24.2', 'P.24.3']),
        'eco_manifest': {('73-15805-0109', 'ALL'): ('E140213', '', ['PCBST', 'PCB2C'], 'P1B'),
                         ('73-15805-0203', 'ALL'): ('E060414', '', ['PCBST', 'PCB2C'], 'P2B'),
                         ('73-15805-0403', 'ALL'): ('E102414', '', ['PCBST', 'PCB2C'], 'PP'),
                         ('73-15805-05B0', 'ALL'): ('EA553365', '91588', ['PCBST', 'PCB2C'], ''),
                         ('73-15805-05A0', 'ALL'): ('EA536264', '76658', ['PCBST', 'PCB2C'], ''),
                         ('73-15805-04B0', 'ALL'): ('EA526167', '73515', ['PCBST', 'PCB2C'], ''),
                         ('73-15805-04A0', 'ALL'): ('EA523543', '67552', ['PCBST', 'PCB2C'], ''),
                         ('73-15805-0404', 'ALL'): ('E102414', '58264', ['PCBST', 'PCB2C'], ''),
                         ('800-43046-03D0', 'ALL'): ('EA555228', '91547', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43046-03B0', 'ALL'): (None, '86996', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43046-03A0', 'ALL'): ('EA536264', '76677', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43046-02C0', 'ALL'): ('EA533983', '76233', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43046-02B0', 'ALL'): ('EA534723', '75661', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43046-02A0', 'ALL'): ('EA526167', '73517', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43046-01D0', 'ALL'): ('EA530824', '72999', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43046-01D0', 'ALL'): (None, '72997', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43046-01C0', 'ALL'): ('EA527875', '70380', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43046-01B0', 'ALL'): ('EA524874', '69472', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43046-01A0', 'ALL'): ('EA523543', '67554', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43046-0117', 'ALL'): ('E102414', '58267', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43046-03D0', 'FTX'): ('EA555228', '92052', ['SYSFT'], ''),
                         ('800-43046-03A0', 'FTX'): ('EA536264', '79747', ['SYSFT'], ''),
                         # ('800-43046-03A0', 'FTX'): (None, '79632', ['SYSFT'], ''),
                         ('800-43046-02C0', 'FTX'): (None, '77255', ['SYSFT'], ''),
                         ('800-43046-01A0', 'FTX'): (None, '77243', ['SYSFT'], ''),
                         # ('800-43046-01A0', 'FTX'): (None, '68767', ['SYSFT'], ''),
                         # ('800-43046-01A0', 'FTX'): (None, '77242', ['SYSFT'], ''),
                         # ('800-43046-01A0', 'FTX'): (None, '69968', ['SYSFT'], ''),
                         ('800-43046-01B0', 'FTX'): (None, '77240', ['SYSFT'], ''),
                         ('800-43046-01D0', 'FTX'): (None, '77239', ['SYSFT'], ''),
                         # ('800-43046-01D0', 'FTX'): (None, '77238', ['SYSFT'], ''),
                         ('800-43046-01C0', 'FTX'): (None, '77237', ['SYSFT'], ''),
                         ('800-43046-02A0', 'FTX'): (None, '77236', ['SYSFT'], ''),
                         ('800-43046-02D0', 'FTX'): (None, '77235', ['SYSFT'], ''),
                         ('800-43046-02B0', 'FTX'): (None, '77233', ['SYSFT'], ''),
                         # ('800-43046-02B0', 'FTX'): (None, '77232', ['SYSFT'], ''),
                         # ('800-43046-02B0', 'FTX'): (None, '77223', ['SYSFT'], ''),
                         },
    },

    'NEWTONCSR24U': {
        'cfg_pids': ['WS-C3850-24U-L', 'WS-C3850-24U-E', 'WS-C3850-24U-S'],
        'MODEL_NUM': 'WS-C3850-24U',
        'MODEL_REVISION_NUM': 'A0',
        'TAN_NUM': '800-43052-03',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-15804-05',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'POE1_SERIAL_NUM': '',
        'POE1_ASSEMBLY_NUM': '73-16439-02',
        'POE1_REVISION_NUM': 'A0',
        'VERSION_ID': 'V01',
        'SBC_CFG':   '',
        'CLEI_CODE_NUMBER': '',
        'ECI_CODE_NUMBER': '',
        'sysinit_required_to_pass': [('Doppler 0 PCIe link lane width is 4', 1)],
        'poe': {'uut_ports': '1-24', 'type': 'UPOE', 'volt_range': (47.0, 56.0), 'current_range': (1008, 1232)},
        'asic': {'type_ids': ['0x3ce'], 'core_count': 1, 'locations': ['U98']},
        'diag_tests': [('PoeDetTest_CSCO',   {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [1], 'mdimode': [0, 1]}}),
                       ('PoeDetTest_IEEE_p', {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [2], 'mdimode': [1], 'poe_type': 'POE+'}}),
                       ('PoeDetTest_IEEE_u', {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [2], 'mdimode': [1], 'poe_type': 'UPOE'}}),
                       ('PoeClassTest_0',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [0]}}),
                       ('PoeClassTest_1',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [1]}}),
                       ('PoeClassTest_2',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [2]}}),
                       ('PoeClassTest_3',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [3]}}),
                       ('PoeClassTest_4',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [4]}}),
                       ('PoePowerTest',      {'cmd': 'PoePowerTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_power_test', 'func_args': {}}),
                       ],
        'traffic_cases': ('traffic_cases_library', '24'),
        'cmpd_types': ('cmpd_type_verify_manifest', ['P.24.1', 'P.24.2', 'P.24.3']),
        'eco_manifest': {('73-100847-0102', 'ALL'): ('E062815', '', ['PCBST', 'PCB2C'], 'SOCKET'),
                         ('73-15804-0109', 'ALL'): ('E140213', '', ['PCBST', 'PCB2C'], 'P1B'),
                         ('73-15804-0203', 'ALL'): ('E060414', '', ['PCBST', 'PCB2C'], 'P2B'),
                         ('73-15804-0302', 'ALL'): ('E081514', '', ['PCBST', 'PCB2C'], 'P3A'),
                         ('73-15804-05B0', 'ALL'): ('EA553365', '91593', ['PCBST', 'PCB2C'], ''),
                         ('73-15804-05A0', 'ALL'): ('EA536264', '76661', ['PCBST', 'PCB2C'], ''),
                         ('73-15804-04B0', 'ALL'): ('EA526167', '73519', ['PCBST', 'PCB2C'], ''),
                         ('73-15804-04A0', 'ALL'): ('EA523543', '67555', ['PCBST', 'PCB2C'], ''),
                         ('73-15804-0403', 'ALL'): ('E102414', '58250', ['PCBST', 'PCB2C'], ''),
                         ('800-43052-03D0', 'ALL'): ('EA555228', '91557', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43052-03B0', 'ALL'): ('EA550394', '86998', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43052-03A0', 'ALL'): ('EA536264', '76679', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43052-02C0', 'ALL'): ('EA533983', '76235', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43052-02B0', 'ALL'): ('EA534723', '75665', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43052-02A0', 'ALL'): ('EA526167', '74374', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43052-01C0', 'ALL'): ('EA530824', '72989', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43052-01B0', 'ALL'): ('EA527875', '70382', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43052-01A0', 'ALL'): ('EA524874', '67557', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43052-0116', 'ALL'): ('E102414', '60232', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43052-01A0', 'FTX'): ('EA523543', '68708', ['SYSFT'], ''),
                         ('800-43052-03D0', 'FTX'): (None, '92253', ['SYSFT'], ''),
                         ('800-43052-03A0', 'FTX'): (None, '79883', ['SYSFT'], ''),
                         # ('800-43052-03A0', 'FTX'): (None, '79882', ['SYSFT'], ''),
                         # ('800-43052-03A0', 'FTX'): (None, '79881', ['SYSFT'], ''),
                         # ('800-43052-03A0', 'FTX'): (None, '79880', ['SYSFT'], ''),
                         # ('800-43052-01A0', 'FTX'): (None, '69938', ['SYSFT'], ''),
                         # ('800-43052-01A0', 'FTX'): (None, '69939', ['SYSFT'], ''),
                         # ('800-43052-01A0', 'FTX'): (None, '69969', ['SYSFT'], ''),
                         ('800-43052-01B0', 'FTX'): (None, '70760', ['SYSFT'], ''),
                         # ('800-43052-01B0', 'FTX'): (None, '72439', ['SYSFT'], ''),
                         ('800-43052-01C0', 'FTX'): (None, '73729', ['SYSFT'], ''),
                         ('800-43052-02A0', 'FTX'): (None, '74375', ['SYSFT'], ''),
                         ('800-43052-02B0', 'FTX'): (None, '76040', ['SYSFT'], ''),
                         ('800-43052-02C0', 'FTX'): (None, '77304', ['SYSFT'], ''),
                         # ('800-43052-02B0', 'FTX'): (None, '77313', ['SYSFT'], ''),
                         },
    },

    'NEWTONCSR48': {
        'cfg_pids': ['WS-C3850-48T-L', 'WS-C3850-48T-E', 'WS-C3850-48T-S'],
        'MODEL_NUM': 'WS-C3850-48T',
        'MODEL_REVISION_NUM': 'A0',
        'TAN_NUM': '800-43043-03',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-16296-07',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'VERSION_ID': 'V01',
        'SBC_CFG':   'NewtonCSR_48PortSKU_SBC_Config_V5.txt',
        'CLEI_CODE_NUMBER': '',
        'ECI_CODE_NUMBER': '',
        'sysinit_required_to_pass': [('Doppler [0-1] PCIe link lane width is 4', 2)],
        'asic': {'type_ids': ['0x3ce'], 'core_count': 2, 'locations': ['U98']},
        'temperature_table': {
            'Exhaust':   {'PCB2C': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 35, 'gb': 0.35},
                                    'HOT':     {'idle': 60,  'traf': 65, 'diag': 65, 'gb': 0.35},
                                    'COLD':    {'idle': 5,   'traf': 20, 'diag': 20, 'gb': 1.00}},
                          'PCBST': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 40, 'gb': 0.35}},
                          'PCBFT': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 40, 'gb': 0.35}},
                          'SYSBI': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 40, 'gb': 0.35}}},
            'Intake':    {'PCB2C': {'AMBIENT': {'idle': 28,  'traf': 28, 'diag': 28, 'gb': 0.35},
                                    'HOT':     {'idle': 60,  'traf': 65, 'diag': 65, 'gb': 0.35},
                                    'COLD':    {'idle': 2.5, 'traf': 10, 'diag': 10, 'gb': 1.00}},
                          'PCBST': {'AMBIENT': {'idle': 32,  'traf': 30, 'diag': 30, 'gb': 0.35}},
                          'PCBFT': {'AMBIENT': {'idle': 32,  'traf': 30, 'diag': 30, 'gb': 0.35}},
                          'SYSBI': {'AMBIENT': {'idle': 32,  'traf': 32, 'diag': 32, 'gb': 0.35}}},
            'Doppler_0': {'PCB2C': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35},
                                    'HOT':     {'idle': 70,  'traf': 80, 'diag': 80, 'gb': 0.35},
                                    'COLD':    {'idle': 10,  'traf': 30, 'diag': 30, 'gb': 1.00}},
                          'PCBST': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}},
                          'PCBFT': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}},
                          'SYSBI': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}}},
            'Doppler_1': {'PCB2C': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35},
                                    'HOT':     {'idle': 70,  'traf': 80, 'diag': 80, 'gb': 0.35},
                                    'COLD':    {'idle': 10,  'traf': 30, 'diag': 30, 'gb': 1.00}},
                          'PCBST': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}},
                          'PCBFT': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}},
                          'SYSBI': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}}},
        },
        'traffic_cases': ('traffic_cases_library', '48'),
        'cmpd_types': ('cmpd_type_verify_manifest', ['T.All.1', 'T.All.2', 'T.All.3']),
        'eco_manifest': {('73-16296-0404', 'ALL'): ('E140213', '', ['PCBST', 'PCB2C'], 'P1B'),
                         ('73-16296-0503', 'ALL'): ('E060414', '', ['PCBST', 'PCB2C'], 'P2B'),
                         ('73-16296-08B0', 'ALL'): ('EA553365', '91584', ['PCBST', 'PCB2C'], ''),
                         ('73-16296-08A0', 'ALL'): ('EA536264', '76663', ['PCBST', 'PCB2C'], ''),
                         ('73-16296-07B0', 'ALL'): ('EA526167', '73523', ['PCBST', 'PCB2C'], ''),
                         ('73-16296-07A0', 'ALL'): ('EA523543', '67561', ['PCBST', 'PCB2C'], ''),
                         ('73-16296-0703', 'ALL'): ('E102414', '58255', ['PCBST', 'PCB2C'], ''),
                         ('800-43043-03D0', 'ALL'): ('EA555228', '91545', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43043-03B0', 'ALL'): ('EA550394', '87000', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43043-03A0', 'ALL'): ('EA536264', '76674', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43043-02C0', 'ALL'): ('EA533983', '75671', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43043-02A0', 'ALL'): ('EA526167', '73525', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43043-01D0', 'ALL'): ('EA530824', '72986', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43043-01C0', 'ALL'): ('EA527875', '70385', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43043-01B0', 'ALL'): ('EA524874', '69470', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43043-01A0', 'ALL'): ('EA523543', '67564', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43043-0116', 'ALL'): ('E102414', '58257', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43043-03D0', 'FTX'): (None, '92064', ['SYSFT'], ''),
                         ('800-43043-03A0', 'FTX'): (None, '81619', ['SYSFT'], ''),
                         ('800-43043-02C0', 'FTX'): (None, 'E74042', ['SYSFT'], ''),
                         ('800-43043-01A0', 'FTX'): (None, '68768', ['SYSFT'], ''),
                         ('800-43043-01B0', 'FTX'): (None, '70150', ['SYSFT'], ''),
                         ('800-43043-01C0', 'FTX'): (None, '70609', ['SYSFT'], ''),
                         ('800-43043-01D0', 'FTX'): (None, '73357', ['SYSFT'], ''),
                         ('800-43043-02A0', 'FTX'): (None, '74042', ['SYSFT'], ''),
                         },
    },

    'NEWTONCSR48P': {
        'cfg_pids': ['WS-C3850-48P-L', 'WS-C3850-48P-E', 'WS-C3850-48P-S', 'WS-C3850-48PW-S',
                     'WS-C3850-48F-L', 'WS-C3850-48F-E', 'WS-C3850-48F-S'],
        'MODEL_NUM': 'WS-C3850-48P',
        'MODEL_REVISION_NUM': 'AC0',
        'TAN_NUM': '800-43041-03',
        'TAN_REVISION_NUMBER': 'D0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-15800-08',
        'MOTHERBOARD_REVISION_NUM': 'B0',
        'POE1_SERIAL_NUM': '',
        'POE1_ASSEMBLY_NUM': '73-16123-03',
        'POE1_REVISION_NUM': 'A0',
        'POE2_SERIAL_NUM': '',
        'POE2_ASSEMBLY_NUM': '73-16123-03',
        'POE2_REVISION_NUM': 'A0',
        'VERSION_ID': 'V01',
        'SBC_CFG':   'NewtonCSR_48PortSKU_SBC_Config_V5.txt',
        'CLEI_CODE_NUMBER': '',
        'ECI_CODE_NUMBER': '',
        'sysinit_required_to_pass': [('Doppler [0-1] PCIe link lane width is 4', 2)],
        'poe': {'uut_ports': '1-48', 'type': 'POE+', 'volt_range': (47.0, 56.0), 'current_range': (486, 594)},
        'asic': {'type_ids': ['0x3ce'], 'core_count': 2, 'locations': ['U98']},
        'temperature_table': {
            'Exhaust':   {'PCB2C': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 35, 'gb': 0.35},
                                    'HOT':     {'idle': 60,  'traf': 65, 'diag': 65, 'gb': 0.35},
                                    'COLD':    {'idle': 5,   'traf': 20, 'diag': 20, 'gb': 1.00}},
                          'PCBST': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 40, 'gb': 0.35}},
                          'PCBFT': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 40, 'gb': 0.35}},
                          'SYSBI': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 40, 'gb': 0.35}}},
            'Intake':    {'PCB2C': {'AMBIENT': {'idle': 28,  'traf': 28, 'diag': 28, 'gb': 0.35},
                                    'HOT':     {'idle': 60,  'traf': 65, 'diag': 65, 'gb': 0.35},
                                    'COLD':    {'idle': 2.5, 'traf': 10, 'diag': 10, 'gb': 1.00}},
                          'PCBST': {'AMBIENT': {'idle': 32,  'traf': 30, 'diag': 30, 'gb': 0.35}},
                          'PCBFT': {'AMBIENT': {'idle': 32,  'traf': 30, 'diag': 30, 'gb': 0.35}},
                          'SYSBI': {'AMBIENT': {'idle': 32,  'traf': 32, 'diag': 32, 'gb': 0.35}}},
            'Doppler_0': {'PCB2C': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35},
                                    'HOT':     {'idle': 70,  'traf': 80, 'diag': 80, 'gb': 0.35},
                                    'COLD':    {'idle': 10,  'traf': 30, 'diag': 30, 'gb': 1.00}},
                          'PCBST': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}},
                          'PCBFT': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}},
                          'SYSBI': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35, 'delta': 35}}},
            'Doppler_1': {'PCB2C': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35},
                                    'HOT':     {'idle': 70,  'traf': 80, 'diag': 80, 'gb': 0.35},
                                    'COLD':    {'idle': 10,  'traf': 30, 'diag': 30, 'gb': 1.00}},
                          'PCBST': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}},
                          'PCBFT': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}},
                          'SYSBI': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35, 'delta': 35}}},
        },
        'diag_tests': [('PoeDetTest_CSCO',   {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [1], 'mdimode': [0, 1]}}),
                       ('PoeDetTest_IEEE',   {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [2], 'mdimode': [1]}}),
                       ('PoeClassTest_0',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [0]}}),
                       ('PoeClassTest_1',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [1]}}),
                       ('PoeClassTest_2',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [2]}}),
                       ('PoeClassTest_3',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [3]}}),
                       ('PoeClassTest_4',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [4]}}),
                       ('PoePowerTest',      {'cmd': 'PoePowerTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_power_test'}),
                       ],
        'traffic_cases': ('traffic_cases_library', '48'),
        'cmpd_types': ('cmpd_type_verify_manifest', ['P.48.1', 'P.48.2', 'P.48.3']),
        'eco_manifest': {('73-15800-0503', 'ALL'): ('E060414', '', ['PCBST', 'PCB2C'], 'P2B'),
                         ('73-15800-08B0', 'ALL'): ('EA553365', '91580', ['PCBST', 'PCB2C'], ''),
                         ('73-15800-08A0', 'ALL'): ('EA536264', '76665', ['PCBST', 'PCB2C'], ''),
                         ('73-15800-07B0', 'ALL'): ('EA526167', '73527', ['PCBST', 'PCB2C'], ''),
                         ('73-15800-07A0', 'ALL'): ('EA523543', '67565', ['PCBST', 'PCB2C'], ''),
                         ('73-15800-0703', 'ALL'): ('E102414', '60747', ['PCBST', 'PCB2C'], ''),
                         ('73-15800-0404', 'ALL'): ('E140213', '58242', ['PCBST', 'PCB2C'], ''),
                         # ('73-15800-0404', 'ALL'): ('E140109', '57629', ['PCBST', 'PCB2C'], ''),
                         # ('73-15800-08A0', 'ALL'): (None, '85174', ['SYSFT'], ''),
                         ('800-43041-03D0', 'ALL'): ('EA555228', '91541', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43041-03B0', 'ALL'): ('EA550394', '87002', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43041-02C0', 'ALL'): ('EA533983', '75677', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43041-02A0', 'ALL'): ('EA526167', '73529', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43041-01D0', 'ALL'): ('EA530824', '73001', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43041-01C0', 'ALL'): ('EA527875', '70387', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43041-01B0', 'ALL'): ('EA524874', '69468', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43041-01A0', 'ALL'): ('EA523543', '67568', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43041-0117', 'ALL'): ('E102414', '60749', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43041-03D0', 'FTX'): (None, '92252', ['SYSFT'], ''),
                         ('800-43041-03A0', 'FTX'): (None, '84898', ['SYSFT'], ''),
                         ('800-43041-02C0', 'FTX'): (None, '79954', ['SYSFT'], ''),
                         # ('800-43041-03A0', 'FTX'): (None, '79441', ['SYSFT'], ''),
                         # ('800-43041-02C0', 'FTX'): (None, '77365', ['SYSFT'], ''),
                         ('800-43041-01A0', 'FTX'): (None, '69837', ['SYSFT'], ''),
                         ('800-43041-01C0', 'FTX'): (None, '70432', ['SYSFT'], ''),
                         ('800-43041-01D0', 'FTX'): (None, '73304', ['SYSFT'], ''),
                         # ('800-43041-01D0', 'FTX'): (None, '73858', ['SYSFT'], ''),
                         # ('800-43041-02C0', 'FTX'): (None, '75813', ['SYSFT'], ''),
                         # ('800-43041-02C0', 'FTX'): (None, '75886', ['SYSFT'], ''),
                         ('800-43041-01B0', 'FTX'): (None, '70280', ['SYSFT'], ''),
                         ('800-43041-02A0', 'FTX'): (None, '73989', ['SYSFT'], ''),
                         # ('800-43041-02A0', 'FTX'): (None, '74281', ['SYSFT'], ''),
                         },
    },

    'NEWTONCSR48U': {
        'cfg_pids': ['WS-C3850-48U-L', 'WS-C3850-48U-E', 'WS-C3850-48U-S'],
        'MODEL_NUM': 'WS-C3850-48U',
        'MODEL_REVISION_NUM': 'A0',
        'TAN_NUM': '800-43050-03',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-15799-08',
        'MOTHERBOARD_REVISION_NUM': 'B0',
        'POE1_SERIAL_NUM': '',
        'POE1_ASSEMBLY_NUM': '73-16439-02',
        'POE1_REVISION_NUM': 'A0',
        'POE2_SERIAL_NUM': '',
        'POE2_ASSEMBLY_NUM': '73-16439-02',
        'POE2_REVISION_NUM': 'A0',
        'VERSION_ID': 'V01',
        'SBC_CFG':   'NewtonCSR_48PortSKU_SBC_Config_V5.txt',
        'sysinit_required_to_pass': [('Doppler [0-1] PCIe link lane width is 4', 2)],
        'poe': {'uut_ports': '1-48', 'type': 'UPOE', 'volt_range': (47.0, 56.0), 'current_range': (1008, 1232)},
        'asic': {'type_ids': ['0x3ce'], 'core_count': 2, 'locations': ['U98']},
        'temperature_table': {
            'Exhaust':   {'PCB2C': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 35, 'gb': 0.35},
                                    'HOT':     {'idle': 60,  'traf': 65, 'diag': 65, 'gb': 0.35},
                                    'COLD':    {'idle': 5,   'traf': 20, 'diag': 20, 'gb': 1.00}},
                          'PCBST': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 40, 'gb': 0.35}},
                          'PCBFT': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 40, 'gb': 0.35}},
                          'SYSBI': {'AMBIENT': {'idle': 36,  'traf': 40, 'diag': 40, 'gb': 0.35}}},
            'Intake':    {'PCB2C': {'AMBIENT': {'idle': 28,  'traf': 28, 'diag': 28, 'gb': 0.35},
                                    'HOT':     {'idle': 60,  'traf': 65, 'diag': 65, 'gb': 0.35},
                                    'COLD':    {'idle': 2.5, 'traf': 10, 'diag': 10, 'gb': 1.00}},
                          'PCBST': {'AMBIENT': {'idle': 32,  'traf': 30, 'diag': 30, 'gb': 0.35}},
                          'PCBFT': {'AMBIENT': {'idle': 32,  'traf': 30, 'diag': 30, 'gb': 0.35}},
                          'SYSBI': {'AMBIENT': {'idle': 32,  'traf': 32, 'diag': 32, 'gb': 0.35}}},
            'Doppler_0': {'PCB2C': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35},
                                    'HOT':     {'idle': 70,  'traf': 80, 'diag': 80, 'gb': 0.35},
                                    'COLD':    {'idle': 10,  'traf': 30, 'diag': 30, 'gb': 1.00}},
                          'PCBST': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}},
                          'PCBFT': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}},
                          'SYSBI': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35, 'delta': 35}}},
            'Doppler_1': {'PCB2C': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35},
                                    'HOT':     {'idle': 70,  'traf': 80, 'diag': 80, 'gb': 0.35},
                                    'COLD':    {'idle': 10,  'traf': 30, 'diag': 30, 'gb': 1.00}},
                          'PCBST': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}},
                          'PCBFT': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35}},
                          'SYSBI': {'AMBIENT': {'idle': 50,  'traf': 50, 'diag': 50, 'gb': 0.35, 'delta': 35}}},
        },
        'diag_tests': [('PoeDetTest_CSCO',   {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [1], 'mdimode': [0, 1]}}),
                       ('PoeDetTest_IEEE_p', {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [2], 'mdimode': [1], 'poe_type': 'POE+'}}),
                       ('PoeDetTest_IEEE_u', {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [2], 'mdimode': [1], 'poe_type': 'UPOE'}}),
                       ('PoeClassTest_0',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [0]}}),
                       ('PoeClassTest_1',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [1]}}),
                       ('PoeClassTest_2',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [2]}}),
                       ('PoeClassTest_3',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [3]}}),
                       ('PoeClassTest_4',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [4]}}),
                       ('PoePowerTest',      {'cmd': 'PoePowerTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_power_test', 'func_args': {}}),
                       ],
        'traffic_cases': ('traffic_cases_library', '48'),
        'cmpd_types': ('cmpd_type_verify_manifest', ['P.48.1', 'P.48.2', 'P.48.3']),
        'eco_manifest': {('73-15799-0404', 'ALL'): ('E140213', '', ['PCBST', 'PCB2C'], 'P1B'),
                         ('73-15799-0503', 'ALL'): ('E051514', '', ['PCBST', 'PCB2C'], 'P2B'),
                         ('73-15799-0602', 'ALL'): ('E081514', '', ['PCBST', 'PCB2C'], 'P3A'),
                         ('73-15799-08B0', 'ALL'): ('EA553365', '91591', ['PCBST', 'PCB2C'], ''),
                         ('73-15799-08A0', 'ALL'): ('EA536264', '76667', ['PCBST', 'PCB2C'], ''),
                         ('73-15799-07B0', 'ALL'): ('EA526167', '73531', ['PCBST', 'PCB2C'], ''),
                         ('73-15799-07A0', 'ALL'): ('EA523543', '67570', ['PCBST', 'PCB2C'], ''),
                         ('73-15799-0703', 'ALL'): ('E102414', '58246', ['PCBST', 'PCB2C'], ''),
                         ('73-15799-0403', 'ALL'): ('E140109', '57626', ['PCBST', 'PCB2C'], ''),
                         ('73-15799-07C0', 'FTX'): (None, '73750', ['SYSFT'], ''),
                         ('800-43050-03D0', 'ALL'): ('EA555228', '91553', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43050-03B0', 'ALL'): ('EA550394', '87004', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43050-03A0', 'ALL'): ('EA536264', '76670', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43050-02C0', 'ALL'): ('EA533983', '75669', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43050-02A0', 'ALL'): ('EA526167', '73533', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43050-01C0', 'ALL'): ('EA530824', '72988', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43050-01A0', 'ALL'): ('E062815', '72427', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43050-01B0', 'ALL'): ('EA527875', '70389', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-43050-01A0', 'ALL'): ('EA524874', '67572', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43050-0116', 'ALL'): ('E102414', '58248', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-43050-01A0', 'FTX'): ('EA523543', '68810', ['SYSFT'], ''),
                         ('800-43050-03D0', 'FTX'): (None, '92177', ['SYSFT'], ''),
                         ('800-43050-03A0', 'FTX'): (None, '80180', ['SYSFT'], ''),
                         ('800-43050-02C0', 'FTX'): (None, '79884', ['SYSFT'], ''),
                         # ('800-43050-02C0', 'FTX'): (None, '74452', ['SYSFT'], ''),
                         # ('800-43050-02C0', 'FTX'): (None, '75998', ['SYSFT'], ''),
                         # ('800-43050-02C0', 'FTX'): (None, '75997', ['SYSFT'], ''),
                         # ('800-43050-01A0', 'FTX'): (None, '69915', ['SYSFT'], ''),
                         ('800-43050-01B0', 'FTX'): (None, '70567', ['SYSFT'], ''),
                         # ('800-43050-01B0', 'FTX'): (None, '72687', ['SYSFT'], ''),
                         ('800-43050-01C0', 'FTX'): (None, '73751', ['SYSFT'], ''),
                         ('800-43050-02A0', 'FTX'): (None, '87190', ['SYSFT'], ''),
                         # ('800-43050-02A0', 'FTX'): (None, '74359', ['SYSFT'], ''),
                         },
    },

}  # family_end
