"""
PRODUCT DEFINITIONS for C3K NewtonCR

The product definition file contains descriptive data about a "family" or set of UUTs for the purposes of test automation.
This file should be atomic to the product family defined by Cisco marketing for release (i.e. DO NOT mix product familiy releases).

Convention:
For embedded dict keys
1. All upper case = flash/cookie parameters
   Note: CMPD data should be used for the latest revision data and per Tst Area if available and/or applicable.
2. All lower case = internal script parameters

Structure:
  family = {
      'COMMON': {...}
      '<PRODUCT_A>': {...}
      '<PRODUCT_B>': {...}
      ...
      '<PRODUCT_N>': {...}
  } # family_end
  Note1: Product "codenames" MUST be used as the '<PRODUCT_X>' names in the family structure.
         This is done to discern the difference between any cost reduced or improved products having the same
         PIDs as it's previous generation (both codename and CPN should be unique).

  WARNING: All dict elements in this structure must be of numeric, str, tuple, list, or dict types.
           Do not use complex elements (e.g. named tuples, imported objects, etc.),
           as this will cause malformed string input for some processing of the ast function.
"""

__title__ = "C3K NewtonCR Product Definitions"
__version__ = '0.2.0'
__family__ = "edison"
__consumer__ = 'c3850.Edison'


family = {
    'COMMON': {
        'product_family': "edison" ,

        # Product Generation: 'GEN1', 'GEN2', 'GEN3'
        'product_generation': 'GEN2',

        # UUT Categories: 'SWITCH', 'UPLINK_MODULE', 'ADAPTER_MODULE', 'CABLE'
        'uut_category': 'SWITCH',

        # Test Area process flow
        'process_flow': ['ICT', 'PCBST', 'PCB2C', 'ASSY', 'SYSBI', 'HIPOT', 'SYSFT'],

        # Flash Params
        'DDR_SPEED': '667',
        'LINUX_COREMASK': '15',
        'STKPWR_SERIAL_NUM': '',
        'STKPWR_ASSEMBLY_NUM': '',
        'STKPWR_REVISION_NUM': '',
        'USB_SERIAL_NUM': '',
        'USB_ASSEMBLY_NUM': '',
        'USB_REVISION_NUM': '',
        'TERMINAL_LINES': '0',
        'MAC_BLOCK_SIZE': '128',

        # Images
        'btldr': {'image': 'cat3k_caa_loader.img.13Mar19.SPA',
                  'rev': {'ver': '', 'date': ''}},
        'linux': {'image': 'vmlinux2013Sep23.mzip.SSA',
                  'rev': ''},
        'diag': {'image': 'stardustThrCR.2014May01',
                 'rev': ''},
        'fpga': {'image': 'bellCrFpga06_01.hex',
                 'rev': '0601',
                 'name': 'bell'},
        # MCU images given by a subdir as the dict keys.
        'mcu': {'images': {'kirch83': ['app_data.srec', 'app_flash.bin', 'kirchhoff_swap.bin', 'Cisco_loader.srec',
                                       'c_kirchhoff_swap_31.bin', 'coulomb_kirchhoff_31.bin']},
                'name': 'alchemy',
                'rev': {'ios': 'APPL 0.74 (0x4a)  38 (0x26)  15 (0x0f)', 'coulomb': 'APPL 0.31 (0x1a)  39 (0x27)  0 (0x00)'}},

        'ios_dirs': {'local': '', 'remote': 'NG3K_IOS'},
        'ios_test_pid': 'S3850UK9-37E',
        'ios_supp_files': {8: [('S3850UK9-32-0SE', 'SR_pkgs'), ('S3850UK9-33SE', 'SR_pkgs')],
                           9: [('ACTUAL', 'recovery')]},

        # settings before IOS main image installation
        'ios_pre_install_params': {'ASIC_PCI_RESET': '1', 'EI_NOPROG': '1'},
        # IOS clean up items
        'ios_cleanup_items': ['obfl', 'crashinfo', 'startup-config'],
        # Rommon params to keep
        'rommon_params_to_keep': ['ASIC_PCI_RESET', 'BOOT_LOADER_UPGRADE_DISABLE' 'SWITCH_NUMBER', 'BOOT', 'BAUD',
                                  'CFG_MODEL_NUM', 'RECOVERY_BUNDLE', 'TERMLINES', 'SBC_CFG', 'MANUAL_BOOT'],
        # default license files/dirs
        'default_license_files': {1: ['tracelogs'],
                                  5: ['dyn_eval', 'eval', 'persist', 'pri', 'red', '*d_license*.*'],
                                  6: ['dyn_eval', 'eval', 'persist', 'pri', 'red', '*d_license*.*']},

        # Identity Protection types: QUACK2, ACT2
        'identity_protection_type': 'QUACK2',  # 'QUACK2',
        # Sequence to program all IdPro, valid types: QUACK, ACT, X509-n (n=1 to total_hashes)
        'idpro_sequence': ['X509-1', 'QUACK', 'X509-2'],
        # Access Point SUDI params
        'x509_sudi_hash': ['SHA1', 'SHA256'],
        'x509_sudi_request_type': 'PROD',
        'x509_sudi_cert_method': 'KEY',
        'hidden_device': '/dev/sda5',

        # ASIC
        'asic': {'type_ids': ['0x0390']},

        # Disk enumeration specifies the rank of all attached disks.  Primary is mandatory and is the target disk for all images (diags & IOS).
        'disk_enums': {'primary': 'sda', 'secondary': None, 'tertiary': None},
        # Flash Device is the directory mapped location of the primary parent mounted device as seen by the bootloader. Relative dir is from the mount point.
        'flash_device': {'name': 'flash', 'relative_dir': 'user', 'device_num': 3},
        # Disk Enumerated Device Mounts must have an ordered precedence for dependent mount locations.
        # Parent mounts are placed first in the list.  Specified mounts should correspond to enumerated disks.
        # Format is a list of tuples: [(<device number>, <mount point>), ...]
        'device_mounts': {
            'primary': [(3, '/mnt'), (1, '/mnt/sd1'), (5, '/mnt/sd5'), (6, '/mnt/sd6'), (7, '/mnt/sd7'), (8, '/mnt/sd8'), (9, '/mnt/sd9')],
            'secondary': None,
            'tertiary': None,
        },
        # Partition definition for each device type.  Populated AFTER the OS determines the device size.
        'partitions': {
            'primary': None,
            'secondary': None,
            'tertiary': None,
        },

        # Fan tests
        'fan': {
            'status_value': '0x0000002A',
            'regs': {'fan1': '0x3C', 'fan2': '0x44', 'fan3': '0x4C'},
            'speed_settings': {'LOW': '0x0A', 'HIGH': '0xFF', 'NOMINAL': '0x7B'},
        },
        # RTC tests
        'rtc': {'time_zone': 'GMT'},

        # StackRac tests
        'stackrac': {'datastack': 1},

        # SerDesEye
        'serdeseye': {'interfaces': ['SIF', 'NIF']},

        # I2C
        'i2c': {
            'target_device_instances': {
                'PCBST': [1, 2, 3],
                'PCB2C': [1, 2, 3],
                'ASSY': [1],
                'PCBFT': [2, 3],
                'SYSBI': [2, 3]},
            'tests': ['SCCTestNonDestructive']
        },

        # SBC params
        'sbc': {'enabled': True, 'temperature_reg': 'READ_TEMPERATURE_2'},

        # PSU
        'psu': {'slots': ['A', 'B']},

        # Configuration check
        'cnf_psu_keys': {'uut_type': ['PID'], 'sn': ['SN']},
        'cnf_pcamap_keys': {'uut_type': ['pid'], 'sn': ['sn']},

        # TST recording
        'pcamap_to_tst_keymap': {'pid': 'uut_type', 'vid': 'version_id', 'sn': 'serial_number', 'hwv': 'tan_hw_rev',
                                 'vpn': 'tan', 'eci': 'eci'},
        'psu_to_tst_keymap': {'PID': 'uut_type', 'SN': 'serial_number', 'TAN': 'tan', 'TAN Rev': 'tan_hw_rev',
                              'VID': 'version_id', 'CLEI': 'clei'},
        'pcamap_items_for_tst': ['1', '2'],

        # Sysinit messages required for passing.
        # Format: list of tuples form of [(<regex message pattern>, <total number of msgs>), (<regex message pattern2>, <total number of msgs>), ...]
        # 'sysinit_required_to_pass': [('Doppler [0-1] PCIe link lane width is 4', 2)],
        # See PRODUCT sections.

        # Chamber Corners (N-Corners)
        #  Format = [('<chamber corner temp+voltage>', adt_enabled), ...]
        #  The temp+voltage designations are 2+2letters:
        #    HT = High Temp,  LT = Low Temp,  HV = High Voltage, LV = Low Voltage, Nx = Nominal/Ambient
        'chamber_corners': [('LTHV', True), ('HTLV', True)],

        # Power cycling test (FST)
        'max_power_cycles': 4,

        # Product Sequence Definition Settings
        # (Parameters that are passed to the sequence definition build-out.)
        'prod_seq_def': {
            'PCBST': {},
            'PCB2C': {},
            'ASSY': {},
            'PCBFT': {'total_loop_time_secs':  3000, 'idpro_periphs': False},
            'SYSBI': {'total_loop_time_secs':  3000, 'idpro_periphs': False},
        },

        # Diag Tests within the Stardust testlist
        # For product-specific tests, place them in the product sections for appending.
        'diag_tests': [('SysMem',          {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('SysRegs',         {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('RTCTest',         {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('UsbDet',          {'areas': ['PCBST', 'PCB2C'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('UsbConsoleLB',    {'areas': ['PCBST', 'PCB2C'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('DopRegs',         {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('DopMem',          {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 1000}),
                       ('DopPSRO',         {'areas': ['PCBST', 'PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('DopMBIST',        {'areas': ['PCBST', 'PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 600}),
                       ('DopLBIST',        {'areas': ['PCBST', 'PCB2C'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('DopInterrupt',    {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('DopNifCiscoPRBS', {'areas': ['PCBST', 'PCB2C'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('DopOffload',      {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 300}),
                       ('SupFrames',       {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 300}),
                       ('SupJumboFrames',  {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 300}),
                       ('PortFrames',      {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 300}),
                       ('JumboFrames',     {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 300}),
                       ('RcpFrames',       {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 300}),
                       ('DebugFrames',     {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 300}),
                       ('OOBM',            {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 300}),
                       ('DopSifCiscoPRBS', {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 300}),
                       ('InsideLoop',      {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 300}),
                       ('Cable',           {'areas': ['PCBST', 'PCB2C'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('PowerDown',       {'areas': ['PCBST', 'PCB2C'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('PortIntrDiag',    {'areas': ['PCBST', 'PCB2C'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('PortCableDiag',   {'areas': ['PCBST', 'PCB2C'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('MacSecBistTest',  {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('MACsecDiag',      {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('EEEDiagTest',     {'areas': ['PCBST', 'PCB2C'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('REProtocol',      {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('REI2C',           {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('AlchemySystem',   {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('AlchemyCommands', {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('PsDet',           {'areas': ['PCBST', 'PCB2C', 'ASSY', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('JJDet',           {'areas': ['ASSY'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('JJReg',           {'areas': ['ASSY'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('JJCtrl',          {'areas': ['ASSY'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('JJBackup',        {'areas': ['ASSY'], 'enabled': False, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('StackPwrDet',     {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ('StackPwrCtrl',    {'areas': ['PCBST', 'PCB2C', 'PCBFT', 'SYSBI'], 'enabled': True, 'adt_enabled': True, 'args': '', 'timeout': 200}),
                       ],

        'traffic_cases_library': {
            '24': {
                'TrafCase_NIF_1': {
                    'downlink_ports': {'1-24': {'speed': '1000'}},
                    'uplink_ports': {'25-26': {'speed': '1000'}, '27-28': {'speed': '10G'}}
                },
                'TrafCase_NIF_2': {
                    'downlink_ports': {'1-24': {'speed': '1000'}},
                    'uplink_ports': {'25-26': {'speed': '10G'}, '27-28': {'speed': '1000'}}
                },
                'TrafCase_EXT_1G_1518_a': {
                    'enabled': True,
                    'areas': ['DBGSYS', 'PCBST', 'ASSY'],
                    'downlink_ports': {
                        '1-24': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'uplink_ports': {
                        '25-26': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '27-28': {'speed': '10G', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'vmargin': 'NOMINAL',
                    'poe_enabled': True,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_1G_1518_b': {
                    'enabled': True,
                    'areas': ['DBGSYS', 'PCBST', 'ASSY'],
                    'downlink_ports': {
                        '1-24': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'uplink_ports': {
                        '25-26': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '27-28': {'speed': '10G', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'vmargin': 'NOMINAL',
                    'poe_enabled': True,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_1G_1518': {
                    'enabled': True,
                    'areas': ['ALL'],
                    'downlink_ports': {
                        '1-24': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'uplink_ports': {
                        '25-26': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '27-28': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'vmargin': 'NOMINAL',
                    'poe_enabled': False,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_1G_64': {
                    'enabled': True,
                    'areas': ['ALL'],
                    'downlink_ports': {
                        '1-24': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'uplink_ports': {
                        '25-26': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '27-28': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True, 'forwarding_schm': 'bridging',
                                  'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'vmargin': 'NOMINAL',
                    'poe_enabled': False,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },

            },
            '48': {
                'TrafCase_NIF_1': {
                    'downlink_ports': {'1-48': {'speed': '1000'}},
                    'uplink_ports': {'49-50,53-54': {'speed': '1000'}, '51-52,55-56': {'speed': '10G'}}
                },
                'TrafCase_NIF_2': {
                    'downlink_ports': {'1-48': {'speed': '1000'}},
                    'uplink_ports': {'49-50,53-54': {'speed': '10G'}, '51-52,55-56': {'speed': '1000'}}
                },
                'TrafCase_EXT_1G_1518_a': {
                    'enabled': True,
                    'areas': ['DBGSYS', 'PCBST', 'ASSY'],
                    'downlink_ports': {
                        '1-48': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'uplink_ports': {
                        '49-50,53-54': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '51-52,55-56': {'speed': '10G', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'vmargin': 'NOMINAL',
                    'poe_enabled': True,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_EXT_1G_1518_b': {
                    'enabled': True,
                    'areas': ['DBGSYS', 'PCBST', 'ASSY'],
                    'downlink_ports': {
                        '1-48': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'uplink_ports': {
                        '49-50,53-54': {'speed': '10G', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '51-52,55-56': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Bidirectional',
                    'loopback_point': 'External',
                    'vmargin': 'NOMINAL',
                    'poe_enabled': True,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_1G_1518': {
                    'enabled': True,
                    'areas': ['ALL'],
                    'downlink_ports': {
                        '1-48': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'uplink_ports': {
                        '49-50,53-54': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '51-52,55-56': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 1518, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'vmargin': 'NOMINAL',
                    'poe_enabled': False,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
                'TrafCase_PHY_1G_64': {
                    'enabled': True,
                    'areas': ['ALL'],
                    'downlink_ports': {
                        '1-48': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True, 'forwarding_schm': 'bridging',
                                 'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'uplink_ports': {
                        '49-50,53-54': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                        '51-52,55-56': {'speed': '1000', 'duplex': 'AUTO', 'crossover': 'AUTO', 'size': 64, 'stress': True, 'forwarding_schm': 'bridging',
                                        'iteration': 1, 'frames_link': 'norestart', 'macsec_mode': 'nomacsec'},
                    },
                    'stackswitching': True,
                    'breakout_ports': {'40G': None, '100G': None},
                    'loopback_direction': 'Forward',
                    'loopback_point': 'PHY0',
                    'vmargin': 'NOMINAL',
                    'poe_enabled': False,
                    'runtime': 120,
                    'pretraf_cmds': [], 'traf_cmds': [],
                },
            },
        },  # traffic_cases

        'cmpd_type_verify_manifest': {
            'T.All.1': {'areas': ['PCBST', 'PCB2C'],
                        'types': ['MAC_ADDR', 'MANUAL_BOOT',
                                  'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                  'MODEL_NUM', 'MODEL_REVISION_NUM',
                                  'DDR_SPEED', 'TERMLINES'
                                  ],
                        },
            'T.All.2': {'areas': ['ASSY', 'SYSBI', 'PCBFT'],
                        'types': ['MAC_ADDR',
                                  'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                  'SYSTEM_SERIAL_NUM', 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                  'STKPWR_ASSEMBLY_NUM', 'STKPWR_REVISION_NUM', 'STKPWR_SERIAL_NUM',
                                  'USB_ASSEMBLY_NUM', 'USB_REVISION_NUM', 'USB_SERIAL_NUM',
                                  'TAN_NUM', 'TAN_REVISION_NUMBER',
                                  'VERSION_ID', 'DDR_SPEED',
                                  'CLEI_CODE_NUMBER', 'ECI_CODE_NUMBER',
                                  ],
                        },
            'T.All.3': {'areas': ['SYSFT'],
                        'types': ['MAC_ADDR',
                                  'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                  'SYSTEM_SERIAL_NUM', 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                  'STKPWR_ASSEMBLY_NUM', 'STKPWR_REVISION_NUM', 'STKPWR_SERIAL_NUM',
                                  'USB_ASSEMBLY_NUM', 'USB_REVISION_NUM', 'USB_SERIAL_NUM',
                                  'TAN_NUM', 'TAN_REVISION_NUMBER',
                                  'VERSION_ID', 'DDR_SPEED',
                                  'CLEI_CODE_NUMBER', 'ECI_CODE_NUMBER',
                                  ],
                        },

            'P.24.1': {'areas': ['PCBST', 'PCB2C'],
                       'types': ['MAC_ADDR', 'MANUAL_BOOT',
                                 'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                 'POE1_ASSEMBLY_NUM', 'POE1_REVISION_NUM', 'POE1_SERIAL_NUM',
                                 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                 'DDR_SPEED', 'TERMLINES'
                                 ],
                       },
            'P.24.2': {'areas': ['ASSY', 'SYSBI', 'PCBFT'],
                       'types': ['MAC_ADDR',
                                 'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                 # 'POE1_ASSEMBLY_NUM', 'POE1_REVISION_NUM', 'POE1_SERIAL_NUM',
                                 'SYSTEM_SERIAL_NUM', 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                 'STKPWR_ASSEMBLY_NUM', 'STKPWR_REVISION_NUM', 'STKPWR_SERIAL_NUM',
                                 'USB_ASSEMBLY_NUM', 'USB_REVISION_NUM', 'USB_SERIAL_NUM',
                                 'TAN_NUM', 'TAN_REVISION_NUMBER',
                                 'VERSION_ID', 'DDR_SPEED',
                                 'CLEI_CODE_NUMBER', 'ECI_CODE_NUMBER',
                                 ],
                       },
            'P.24.3': {'areas': ['SYSFT'],
                       'types': ['MAC_ADDR',
                                 'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                 'POE1_ASSEMBLY_NUM', 'POE1_REVISION_NUM', 'POE1_SERIAL_NUM',
                                 'SYSTEM_SERIAL_NUM', 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                 'STKPWR_ASSEMBLY_NUM', 'STKPWR_REVISION_NUM', 'STKPWR_SERIAL_NUM',
                                 'USB_ASSEMBLY_NUM', 'USB_REVISION_NUM', 'USB_SERIAL_NUM',
                                 'TAN_NUM', 'TAN_REVISION_NUMBER',
                                 'VERSION_ID', 'DDR_SPEED',
                                 'CLEI_CODE_NUMBER', 'ECI_CODE_NUMBER',
                                 ],
                       },
            'P.48.1': {'areas': ['PCBST', 'PCB2C'],
                       'types': ['MAC_ADDR', 'MANUAL_BOOT',
                                 'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                 'POE1_ASSEMBLY_NUM', 'POE1_REVISION_NUM', 'POE1_SERIAL_NUM',
                                 'POE2_ASSEMBLY_NUM', 'POE2_REVISION_NUM', 'POE2_SERIAL_NUM',
                                 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                 'DDR_SPEED', 'TERMLINES'
                                 ],
                       },
            'P.48.2': {'areas': ['ASSY', 'SYSBI', 'PCBFT'],
                       'types': ['MAC_ADDR',
                                 'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                 # 'POE1_ASSEMBLY_NUM', 'POE1_REVISION_NUM', 'POE1_SERIAL_NUM',
                                 # 'POE2_ASSEMBLY_NUM', 'POE2_REVISION_NUM', 'POE2_SERIAL_NUM',
                                 'SYSTEM_SERIAL_NUM', 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                 'STKPWR_ASSEMBLY_NUM', 'STKPWR_REVISION_NUM', 'STKPWR_SERIAL_NUM',
                                 'USB_ASSEMBLY_NUM', 'USB_REVISION_NUM', 'USB_SERIAL_NUM',
                                 'TAN_NUM', 'TAN_REVISION_NUMBER',
                                 'VERSION_ID', 'DDR_SPEED',
                                 'CLEI_CODE_NUMBER', 'ECI_CODE_NUMBER',
                                 ],
                       },
            'P.48.3': {'areas': ['SYSFT'],
                       'types': ['MAC_ADDR',
                                 'MOTHERBOARD_ASSEMBLY_NUM', 'MOTHERBOARD_REVISION_NUM', 'MOTHERBOARD_SERIAL_NUM',
                                 'POE1_ASSEMBLY_NUM', 'POE1_REVISION_NUM', 'POE1_SERIAL_NUM',
                                 'POE2_ASSEMBLY_NUM', 'POE2_REVISION_NUM', 'POE2_SERIAL_NUM',
                                 'SYSTEM_SERIAL_NUM', 'MODEL_NUM', 'MODEL_REVISION_NUM',
                                 'STKPWR_ASSEMBLY_NUM', 'STKPWR_REVISION_NUM', 'STKPWR_SERIAL_NUM',
                                 'USB_ASSEMBLY_NUM', 'USB_REVISION_NUM', 'USB_SERIAL_NUM',
                                 'TAN_NUM', 'TAN_REVISION_NUMBER',
                                 'VERSION_ID', 'DDR_SPEED',
                                 'CLEI_CODE_NUMBER', 'ECI_CODE_NUMBER',
                                 ],
                       },

        },  # cmpd

    },

    'NEWTONCR24': {
        'cfg_pids': ['WS-C3850-24T-L', 'WS-C3850-24T-E', 'WS-C3850-24T-S'],
        'MODEL_NUM': 'WS-C3850-24T',
        'MODEL_REVISION_NUM': 'L0',
        'TAN_NUM': '800-37560-02',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-14443-08',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'VERSION_ID': 'V03',
        'SBC_CFG':   '17-11228-04.SBC_cfg',
        'CLEI_CODE_NUMBER': '',
        'ECI_CODE_NUMBER': '',
        'sysinit_required_to_pass': [('Doppler 0 PCIe link lane width is 4', 1)],
        'asic': {'core_count': 1, 'locations': ['U6']},
        'traffic_cases': ('traffic_cases_library', '24'),
        'cmpd_types': ('cmpd_type_verify_manifest', ['T.All.1', 'T.All.2', 'T.All.3']),
        'eco_manifest': {('73-14443-08A0', 'ALL'): ('EA520237', '', ['PCBST', 'PCB2C'], ''),
                         ('73-14443-07A0', 'ALL'): ('E118960', '61466', ['PCBST', 'PCB2C'], ''),
                         ('73-14443-06A0', 'ALL'): ('E117079', '56868', ['PCBST', 'PCB2C'], ''),
                         ('73-14443-05D0', 'ALL'): ('E115831', '56347', ['PCBST', 'PCB2C'], ''),
                         ('73-14443-05C0', 'ALL'): ('E115320', '54821', ['PCBST', 'PCB2C'], ''),
                         ('73-14443-05B0', 'ALL'): ('E114753', '48593', ['PCBST', 'PCB2C'], ''),
                         ('73-14443-05A0', 'ALL'): ('E113614', '51862', ['PCBST', 'PCB2C'], ''),
                         ('73-14443-0401', 'ALL'): ('E201206', '46166', ['PCBST', 'PCB2C'], ''),
                         ('73-14443-0307', 'ALL'): ('E201301', '50517', ['PCBST', 'PCB2C'], ''),
                         ('800-37560-03D0', 'ALL'): ('EA527875', '70357', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37560-03C0', 'ALL'): ('EA520237', '66096', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37560-03A0', 'ALL'): ('E118960', '61481', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37560-02B0', 'ALL'): ('E119304', '59208', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37560-02A0', 'ALL'): ('E117079', '56936', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37560-01H0', 'ALL'): ('E115831', '56349', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37560-01F0', 'ALL'): ('E115667', '54553', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37560-01E0', 'ALL'): ('E115320', '54824', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37560-01G0', 'ALL'): ('E115956', '55019', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37560-01D0', 'ALL'): ('E114944', '55076', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37560-01B0', 'ALL'): ('E113835', '52161', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37560-01A0', 'ALL'): ('E113364', '51871', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37560-0146', 'ALL'): ('E201206', '46168', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37560-0145', 'ALL'): ('E201301', '50520', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37560-01D0', 'ALL'): (None, '48771', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37560-02A0', 'FTX'): (None, '67196', ['SYSFT'], ''),
                         # ('800-37560-02A0', 'FTX'): (None, '57495', ['SYSFT'], ''),
                         ('800-37560-01B0', 'FTX'): (None, '57349', ['SYSFT'], ''),
                         ('800-37560-01G0', 'FTX'): (None, '55408', ['SYSFT'], ''),
                         ('800-37560-01H0', 'FTX'): (None, '56927', ['SYSFT'], ''),
                         ('800-37560-01D0', 'FTX'): (None, '56097', ['SYSFT'], ''),
                         # ('800-37560-01G0', 'FTX'): (None, '56036', ['SYSFT'], ''),
                         ('800-37560-01F0', 'FTX'): (None, '55411', ['SYSFT'], ''),
                         # ('800-37560-01F0', 'FTX'): (None, '55238', ['SYSFT'], ''),
                         # ('800-37560-01D0', 'FTX'): (None, '55078', ['SYSFT'], ''),
                         # ('800-37560-01B0', 'FTX'): (None, '55077', ['SYSFT'], ''),
                         # ('800-37560-01D0', 'FTX'): (None, '54250', ['SYSFT'], ''),
                         ('800-37560-01A0', 'FTX'): (None, '52781', ['SYSFT'], ''),
                         # ('800-37560-01B0', 'FTX'): (None, '52532', ['SYSFT'], ''),
                         ('800-37560-03D0', 'FTX'): (None, '71056', ['SYSFT'], ''),
                         ('800-37560-03C0', 'FTX'): (None, '66805', ['SYSFT'], ''),
                         ('800-37560-03A0', 'FTX'): (None, '61838', ['SYSFT'], ''),
                         },

    },

    'NEWTONCR24P': {
        'cfg_pids': ['WS-C3850-24P-L', 'WS-C3850-24P-E', 'WS-C3850-24P-S', 'WS-C3850-24PW-S'],
        'MODEL_NUM': 'WS-C3850-24P',
        'MODEL_REVISION_NUM': 'L0',
        'TAN_NUM': '800-37562-02',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-14441-10',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'POE1_SERIAL_NUM': '',
        'POE1_ASSEMBLY_NUM': '73-14095-01',
        'POE1_REVISION_NUM': 'B0',
        'VERSION_ID': 'V03',
        'SBC_CFG':   '17-11228-04.SBC_cfg',
        'CLEI_CODE_NUMBER': '',
        'ECI_CODE_NUMBER': '',
        'sysinit_required_to_pass': [('Doppler 0 PCIe link lane width is 4', 1)],
        'asic': {'core_count': 1, 'locations': ['U6']},
        'poe': {'uut_ports': '1-24', 'type': 'POE+', 'volt_range': (47.0, 56.0), 'current_range': (486, 594)},
        'diag_tests': [('PoeDetTest_CSCO',   {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [1], 'mdimode': [0, 1]}}),
                       ('PoeDetTest_IEEE',   {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [2], 'mdimode': [1]}}),
                       ('PoeClassTest_0',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [0]}}),
                       ('PoeClassTest_1',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [1]}}),
                       ('PoeClassTest_2',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [2]}}),
                       ('PoeClassTest_3',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [3]}}),
                       ('PoeClassTest_4',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [4]}}),
                       ('PoePowerTest',      {'cmd': 'PoePowerTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_power_test'}),
                       ],
        'traffic_cases': ('traffic_cases_library', '24'),
        'cmpd_types': ('cmpd_type_verify_manifest', ['P.24.1', 'P.24.2', 'P.24.3']),
        'eco_manifest': {('73-14441-10A0', 'ALL'): ('EA520237', '66089', ['PCBST', 'PCB2C'], ''),
                         ('73-14441-08A0', 'ALL'): ('E118960', '61462', ['PCBST', 'PCB2C'], ''),
                         ('73-14441-07A0', 'ALL'): ('E117079', '56864', ['PCBST', 'PCB2C'], ''),
                         ('73-14441-06D0', 'ALL'): ('E115831', '56334', ['PCBST', 'PCB2C'], ''),
                         ('73-14441-06C0', 'ALL'): ('E115320', '54806', ['PCBST', 'PCB2C'], ''),
                         ('73-14441-06B0', 'ALL'): ('E114753', '48245', ['PCBST', 'PCB2C'], ''),
                         ('73-14441-06A0', 'ALL'): ('E113614', '51851', ['PCBST', 'PCB2C'], ''),
                         ('73-14441-0501', 'ALL'): ('E201206', '46157', ['PCBST', 'PCB2C'], ''),
                         ('73-14441-0406', 'ALL'): ('E201301', '50518', ['PCBST', 'PCB2C'], ''),
                         ('800-37562-03A0', 'ALL'): ('E118960', '61750', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37562-02A0', 'ALL'): ('E117079', '61710', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37562-01D0', 'ALL'): ('E114944', '58346', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37562-01G0', 'ALL'): ('E115956', '58329', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37562-01F0', 'ALL'): ('E115667', '58328', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37562-01H0', 'ALL'): ('E115831', '58137', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37562-01B0', 'ALL'): ('E113835', '54953', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37562-01A0', 'ALL'): ('E113364', '52786', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37562-04D0', 'ALL'): ('EA527875', '70358', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37562-04C0', 'ALL'): ('EA520237', '66091', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37562-03A0', 'ALL'): (None, '61482', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37562-02B0', 'ALL'): ('E119304', '59205', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37562-02A0', 'ALL'): (None, '56938', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37562-01F0', 'ALL'): (None, '54559', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37562-01D0', 'ALL'): (None, '48344', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37562-01G0', 'ALL'): (None, '55024', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-32656-01D0', 'ALL'): (None, '51491', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37562-01H0', 'ALL'): (None, '56336', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37562-01E0', 'ALL'): ('E115320', '54809', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37562-01B0', 'ALL'): (None, '52156', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37562-01A0', 'ALL'): (None, '51872', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37562-0146', 'ALL'): ('E201206', '46159', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37562-0145', 'ALL'): ('E201301', '50523', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37562-03A0', 'FTX'): (None, '61746', ['SYSFT'], ''),
                         # ('800-37562-03A0', 'FTX'): (None, '61592', ['SYSFT'], ''),
                         ('800-37562-01G0', 'FTX'): (None, '58326', ['SYSFT'], ''),
                         ('800-37562-01D0', 'FTX'): (None, '58139', ['SYSFT'], ''),
                         # ('800-37562-01D0', 'FTX'): (None, '57994', ['SYSFT'], ''),
                         ('800-37562-01H0', 'FTX'): (None, '57737', ['SYSFT'], ''),
                         ('800-37562-02A0', 'FTX'): (None, '57738', ['SYSFT'], ''),
                         # ('800-37562-02A0', 'FTX'): (None, '57512', ['SYSFT'], ''),
                         # ('800-37562-01H0', 'FTX'): (None, '57453', ['SYSFT'], ''),
                         # ('800-37562-01G0', 'FTX'): (None, '56635', ['SYSFT'], ''),
                         # ('800-37562-01G0', 'FTX'): (None, '56076', ['SYSFT'], ''),
                         ('800-37562-01F0', 'FTX'): (None, '55531', ['SYSFT'], ''),
                         # ('800-37562-01G0', 'FTX'): (None, '55448', ['SYSFT'], ''),
                         # ('800-37562-01F0', 'FTX'): (None, '55429', ['SYSFT'], ''),
                         # ('800-37562-01F0', 'FTX'): (None, '55428', ['SYSFT'], ''),
                         # ('800-37562-01F0', 'FTX'): (None, '55356', ['SYSFT'], ''),
                         # ('800-37562-01F0', 'FTX'): (None, '55352', ['SYSFT'], ''),
                         # ('800-37562-01F0', 'FTX'): (None, '55086', ['SYSFT'], ''),
                         ('800-37562-01B0', 'FTX'): (None, '54952', ['SYSFT'], ''),
                         # ('800-37562-01D0', 'FTX'): (None, '54492', ['SYSFT'], ''),
                         # ('800-37562-01B0', 'FTX'): (None, '53977', ['SYSFT'], ''),
                         # ('800-37562-01D0', 'FTX'): (None, '53936', ['SYSFT'], ''),
                         # ('800-37562-01D0', 'FTX'): (None, '53933', ['SYSFT'], ''),
                         # ('800-37562-01B0', 'FTX'): (None, '52782', ['SYSFT'], ''),
                         ('800-37562-04A0', 'FTX'): (None, '77245', ['SYSFT'], ''),
                         # ('800-37562-04A0', 'FTX'): (None, 'EA518108', ['SYSFT'], ''),
                         ('800-37562-04C0', 'FTX'): (None, '77244', ['SYSFT'], ''),
                         # ('800-37562-04C0', 'FTX'): (None, '67136', ['SYSFT'], ''),
                         ('800-37562-04D0', 'FTX'): (None, '77241', ['SYSFT'], ''),
                         },

    },

    'NEWTONCR24U': {
        'cfg_pids': ['WS-C3850-24U-L', 'WS-C3850-24U-E', 'WS-C3850-24U-S'],
        'MODEL_NUM': 'WS-C3850-24U',
        'MODEL_REVISION_NUM': 'E0',
        'TAN_NUM': '800-38772-02',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-14984-08',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'POE1_SERIAL_NUM': '',
        'POE1_ASSEMBLY_NUM': '73-14909-02',
        'POE1_REVISION_NUM': 'B0',
        'VERSION_ID': 'V03',
        'SBC_CFG':   '17-11228-04.SBC_cfg',
        'CLEI_CODE_NUMBER': '',
        'ECI_CODE_NUMBER': '',
        'sysinit_required_to_pass': [('Doppler 0 PCIe link lane width is 4', 1)],
        'asic': {'core_count': 1, 'locations': ['U6']},
        'poe': {'uut_ports': '1-24', 'type': 'UPOE', 'volt_range': (47.0, 56.0), 'current_range': (1008, 1232)},
        'traffic_cases': ('traffic_cases_library', '24'),
        'diag_tests': [('PoeDetTest_CSCO',   {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [1], 'mdimode': [0, 1]}}),
                       ('PoeDetTest_IEEE_p', {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [2], 'mdimode': [1], 'poe_type': 'POE+'}}),
                       ('PoeDetTest_IEEE_u', {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [2], 'mdimode': [1], 'poe_type': 'UPOE'}}),
                       ('PoeClassTest_0',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [0]}}),
                       ('PoeClassTest_1',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [1]}}),
                       ('PoeClassTest_2',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [2]}}),
                       ('PoeClassTest_3',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [3]}}),
                       ('PoeClassTest_4',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [4]}}),
                       ('PoePowerTest',      {'cmd': 'PoePowerTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_power_test', 'func_args': {}}),
                       ],
        'cmpd_types': ('cmpd_type_verify_manifest', ['P.24.1', 'P.24.2', 'P.24.3']),
        'eco_manifest': {('73-100847-0102', 'ALL'): ('E062815', '', ['PCBST', 'PCB2C'], 'SOCKET'),
                         ('73-14984-08A0', 'ALL'): ('EA520237', '66099', ['PCBST', 'PCB2C'], ''),
                         ('73-14984-07A0', 'ALL'): ('E118960', '61472', ['PCBST', 'PCB2C'], ''),
                         ('73-14984-06A0', 'ALL'): ('E117079', '56880', ['PCBST', 'PCB2C'], ''),
                         ('73-14984-05A0', 'ALL'): ('E115090', '46645', ['PCBST', 'PCB2C'], ''),
                         ('800-38772-03E0', 'ALL'): ('EA530824', '73002', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38772-03D0', 'ALL'): ('EA527875', '70360', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38772-03C0', 'ALL'): ('EA520237', '66101', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38772-03A0', 'ALL'): ('E118960', '61489', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38772-02A0', 'ALL'): ('E117079', '56945', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38772-02B0', 'ALL'): ('E119304', '59211', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38772-01B0', 'ALL'): ('E115022', '46647', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38772-01E0', 'ALL'): ('E117273', '56121', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38772-01D0', 'ALL'): ('E115956', '55029', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38772-01C0', 'ALL'): ('E115667', None, ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38772-03D0', 'FTX'): (None, '72745', ['SYSFT'], ''),
                         ('800-38772-03C0', 'FTX'): (None, '67347', ['SYSFT'], ''),
                         ('800-38772-03A0', 'FTX'): (None, '65722', ['SYSFT'], ''),
                         # ('800-38772-03A0', 'FTX'): (None, '62180', ['SYSFT'], ''),
                         ('800-38772-01E0', 'FTX'): (None, '61438', ['SYSFT'], ''),
                         # ('800-38772-01E0', 'FTX'): (None, '59080', ['SYSFT'], ''),
                         # ('800-38772-01E0', 'FTX'): (None, '59073', ['SYSFT'], ''),
                         ('800-38772-01B0', 'FTX'): (None, '57813', ['SYSFT'], ''),
                         # ('800-38772-01B0', 'FTX'): (None, '57811', ['SYSFT'], ''),
                         ('800-38772-01D0', 'FTX'): (None, '57622', ['SYSFT'], ''),
                         ('800-38772-02A0', 'FTX'): (None, '57377', ['SYSFT'], ''),
                         # ('800-38772-01B0', 'FTX'): (None, '55030', ['SYSFT'], ''),
                         },

    },

    'NEWTONCR48': {
        'cfg_pids': ['WS-C3850-48T-L', 'WS-C3850-48T-E', 'WS-C3850-48T-S'],
        'MODEL_NUM': 'WS-C3850-48T',
        'MODEL_REVISION_NUM': 'M0',
        'TAN_NUM': '800-37552-02',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-14444-07',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'VERSION_ID': 'V03',
        'SBC_CFG':   '17-11225-05.SBC_cfg',
        'CLEI_CODE_NUMBER': '',
        'ECI_CODE_NUMBER': '',
        'sysinit_required_to_pass': [('Doppler [0-1] PCIe link lane width is 4', 2)],
        'asic': {'core_count': 2, 'locations': ['U6', 'U7']},
        'traffic_cases': ('traffic_cases_library', '48'),
        'cmpd_types': ('cmpd_type_verify_manifest', ['T.All.1', 'T.All.2', 'T.All.3']),
        'eco_manifest': {('73-14444-07A0', 'ALL'): ('E118960', '61468', ['PCBST', 'PCB2C'], ''),
                         ('73-14444-06A0', 'ALL'): ('E117079', '56873', ['PCBST', 'PCB2C'], ''),
                         ('73-14444-05D0', 'ALL'): ('E115831', '56351', ['PCBST', 'PCB2C'], ''),
                         ('73-14444-05C0', 'ALL'): ('E115320', '54826', ['PCBST', 'PCB2C'], ''),
                         ('73-14444-05E0', 'ALL'): (None, '54082', ['PCBST', 'PCB2C'], ''),
                         ('73-14444-05B0', 'ALL'): ('E114753', '49298', ['PCBST', 'PCB2C'], ''),
                         ('73-14444-05A1', 'ALL'): ('E113894', '51861', ['PCBST', 'PCB2C'], ''),
                         ('73-14444-0402', 'ALL'): ('E201206', '46169', ['PCBST', 'PCB2C'], ''),
                         ('73-14444-0307', 'ALL'): ('E201301', '50522', ['PCBST', 'PCB2C'], ''),
                         ('800-37552-03C0', 'ALL'): ('EA527875', '70363', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37552-03B0', 'ALL'): ('EA520469', '66910', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37552-03A0', 'ALL'): ('E118960', '61479', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37552-02B0', 'ALL'): ('E119304', '59210', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37552-02A0', 'ALL'): ('E117079', '56934', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37552-01J0', 'ALL'): ('E115831', '56354', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37552-01H0', 'ALL'): ('E115956', '55021', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37552-01F0', 'ALL'): ('E115320', '54828', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37552-01G0', 'ALL'): ('E115667', '54557', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37552-01E0', 'ALL'): ('E114944', '53157', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37552-01C0', 'ALL'): ('E114753', '49563', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37552-01B0', 'ALL'): ('E113835', '52174', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37552-01A0', 'ALL'): ('E113364', '51867', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37552-0147', 'ALL'): ('E201206', '46173', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37552-0145', 'ALL'): ('E201301', '50527', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37552-03C0', 'FTX'): (None, '73015', ['SYSFT'], ''),
                         ('800-37552-03B0', 'FTX'): (None, '68329', ['SYSFT'], ''),
                         ('800-37552-03A0', 'FTX'): (None, '61718', ['SYSFT'], ''),
                         # ('800-37552-03A0', 'FTX'): (None, '61653', ['SYSFT'], ''),
                         ('800-37552-01H0', 'FTX'): (None, '58751', ['SYSFT'], ''),
                         # ('800-37552-01H0', 'FTX'): (None, '58544', ['SYSFT'], ''),
                         # ('800-37552-01H0', 'FTX'): (None, '58128', ['SYSFT'], ''),
                         ('800-37552-01E0', 'FTX'): (None, '58032', ['SYSFT'], ''),
                         # ('800-37552-01E0', 'FTX'): (None, '58031', ['SYSFT'], ''),
                         ('800-37552-02A0', 'FTX'): (None, '57375', ['SYSFT'], ''),
                         ('800-37552-01J0', 'FTX'): (None, '57102', ['SYSFT'], ''),
                         # ('800-37552-01H0', 'FTX'): (None, '56016', ['SYSFT'], ''),
                         # ('800-37552-01H0', 'FTX'): (None, '55969', ['SYSFT'], ''),
                         # ('800-32655-01D0', 'FTX'): (None, '55967', ['SYSFT'], ''),
                         # ('800-37552-01E0', 'FTX'): (None, '55933', ['SYSFT'], ''),
                         ('800-37552-01G0', 'FTX'): (None, '55913', ['SYSFT'], ''),
                         # ('800-37552-01G0', 'FTX'): (None, '54984', ['SYSFT'], ''),
                         # ('800-37552-01H0', 'FTX'): (None, '55436', ['SYSFT'], ''),
                         ('800-37552-01B0', 'FTX'): (None, '54940', ['SYSFT'], ''),
                         # ('800-32655-01D0', 'FTX'): (None, '54804', ['SYSFT'], ''),
                         ('800-37552-01F0', 'FTX'): (None, '54799', ['SYSFT'], ''),
                         # ('800-37552-01E0', 'FTX'): (None, '54603', ['SYSFT'], ''),
                         # ('800-37552-01E0', 'FTX'): (None, '54085', ['SYSFT'], ''),
                         # ('800-37552-01E0', 'FTX'): (None, '54084', ['SYSFT'], ''),
                         # ('800-37552-01B0', 'FTX'): (None, '52731', ['SYSFT'], ''),
                         ('800-37552-01A0', 'FTX'): (None, '52659', ['SYSFT'], ''),
                         # ('800-37552-01A0', 'FTX'): (None, '52543', ['SYSFT'], ''),
                         },

    },

    'NEWTONCR48P': {
        'cfg_pids': ['WS-C3850-48P-L', 'WS-C3850-48P-E', 'WS-C3850-48P-S', 'WS-C3850-48PW-S',
                     'WS-C3850-48F-L', 'WS-C3850-48F-E', 'WS-C3850-48F-S'],
        'MODEL_NUM': 'WS-C3850-48P',
        'MODEL_REVISION_NUM': 'M0',
        'TAN_NUM': '800-37564-02',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-14442-10',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'POE1_SERIAL_NUM': '',
        'POE1_ASSEMBLY_NUM': '73-14095-01',
        'POE1_REVISION_NUM': 'B0',
        'POE2_SERIAL_NUM': '',
        'POE2_ASSEMBLY_NUM': '73-14095-01',
        'POE2_REVISION_NUM': 'B0',
        'VERSION_ID': 'V03',
        'SBC_CFG':   '17-11225-05.SBC_cfg',
        'CLEI_CODE_NUMBER': '',
        'ECI_CODE_NUMBER': '',
        'sysinit_required_to_pass': [('Doppler [0-1] PCIe link lane width is 4', 2)],
        'asic': {'core_count': 2, 'locations': ['U6', 'U7']},
        'poe': {'uut_ports': '1-48', 'type': 'POE+', 'volt_range': (47.0, 56.0), 'current_range': (486, 594)},
        'diag_tests': [('PoeDetTest_CSCO',   {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [1], 'mdimode': [0, 1]}}),
                       ('PoeDetTest_IEEE',   {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [2], 'mdimode': [1]}}),
                       ('PoeClassTest_0',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [0]}}),
                       ('PoeClassTest_1',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [1]}}),
                       ('PoeClassTest_2',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [2]}}),
                       ('PoeClassTest_3',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [3]}}),
                       ('PoeClassTest_4',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [4]}}),
                       ('PoePowerTest',      {'cmd': 'PoePowerTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_power_test'}),
                       ],
        'traffic_cases': ('traffic_cases_library', '48'),
        'cmpd_types': ('cmpd_type_verify_manifest', ['P.48.1', 'P.48.2', 'P.48.3']),
        'eco_manifest': {('73-14442-10A0', 'ALL'): ('E118960', '61464', ['PCBST', 'PCB2C'], ''),
                         ('73-14442-09A0', 'ALL'): ('E117079', '56866', ['PCBST', 'PCB2C'], ''),
                         ('73-14442-08D0', 'ALL'): ('E115831', '56343', ['PCBST', 'PCB2C'], ''),
                         ('73-14442-08C0', 'ALL'): ('E115320', '54814', ['PCBST', 'PCB2C'], ''),
                         ('73-14442-08B0', 'ALL'): ('E114753', '48946', ['PCBST', 'PCB2C'], ''),
                         ('73-14442-08A1', 'ALL'): ('E113894', '51848', ['PCBST', 'PCB2C'], ''),
                         ('73-14442-0702', 'ALL'): ('E201206', '46161', ['PCBST', 'PCB2C'], ''),
                         ('73-14442-0607', 'ALL'): ('E201301', '50529', ['PCBST', 'PCB2C'], ''),
                         ('800-37564-03C0', 'ALL'): ('EA527875', '77364', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37564-03B0', 'ALL'): ('EA520469', '67590', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37564-03A0', 'ALL'): ('E118960', '61779', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37564-01H0', 'ALL'): ('E115956', '58769', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37564-01J0', 'ALL'): ('E115831', '58740', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37564-02A0', 'ALL'): ('E117079', '58213', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37564-01B0', 'ALL'): ('E113835', '57378', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37564-01E0', 'ALL'): ('E114944', '57285', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37564-01G0', 'ALL'): ('E115667', '55457', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37564-01A0', 'ALL'): ('E113364', '52763', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37564-02B0', 'ALL'): ('E119304', '59204', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37564-01F0', 'ALL'): ('E115320', '54820', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37564-01C0', 'ALL'): ('E114753', '49228', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37564-0147', 'ALL'): ('E201206', '46164', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37564-0145', 'ALL'): ('E201301', '50531', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37564-03C0', 'ALL'): (None, '70365', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37564-03B0', 'ALL'): (None, '66912', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37564-03A0', 'ALL'): (None, '61485', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37564-01H0', 'ALL'): (None, '55023', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37564-02A0', 'ALL'): (None, '56941', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37564-01J0', 'ALL'): (None, '56345', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37564-01B0', 'ALL'): (None, '52163', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37564-01E0', 'ALL'): (None, '53155', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37564-01G0', 'ALL'): (None, '54565', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         # ('800-37564-01A0', 'ALL'): (None, '51869', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-37564-03C0', 'FTX'): (None, '70945', ['SYSFT'], ''),
                         ('800-37564-03A0', 'FTX'): (None, '61451', ['SYSFT'], ''),
                         ('800-37564-02A0', 'FTX'): (None, '58029', ['SYSFT'], ''),
                         ('800-37564-01H0', 'FTX'): (None, '57429', ['SYSFT'], ''),
                         ('800-37564-01J0', 'FTX'): (None, '57423', ['SYSFT'], ''),
                         ('800-37564-01E0', 'FTX'): (None, '57275', ['SYSFT'], ''),
                         # ('800-37564-01E0', 'FTX'): (None, '57274', ['SYSFT'], ''),
                         # ('800-37564-02A0', 'FTX'): (None, '57250', ['SYSFT'], ''),
                         ('800-37564-01B0', 'FTX'): (None, '57195', ['SYSFT'], ''),
                         # ('800-37564-01J0', 'FTX'): (None, '57013', ['SYSFT'], ''),
                         # ('800-37564-01J0', 'FTX'): (None, '56634', ['SYSFT'], ''),
                         # ('800-37564-01H0', 'FTX'): (None, '55970', ['SYSFT'], ''),
                         # ('800-37564-01H0', 'FTX'): (None, '55934', ['SYSFT'], ''),
                         # ('800-37564-01H0', 'FTX'): (None, '55847', ['SYSFT'], ''),
                         # ('800-37564-01E0', 'FTX'): (None, '55536', ['SYSFT'], ''),
                         # ('800-37564-01H0', 'FTX'): (None, '55456', ['SYSFT'], ''),
                         ('800-37564-01G0', 'FTX'): (None, '55450', ['SYSFT'], ''),
                         # ('800-37564-01G0', 'FTX'): (None, '55190', ['SYSFT'], ''),
                         # ('800-37564-01G0', 'FTX'): (None, '55098', ['SYSFT'], ''),
                         # ('800-37564-01E0', 'FTX'): (None, '54796', ['SYSFT'], ''),
                         # ('800-32657-01D0', 'FTX'): (None, '54734', ['SYSFT'], ''),
                         # ('800-37564-01E0', 'FTX'): (None, '54431', ['SYSFT'], ''),
                         # ('800-37564-01E0', 'FTX'): (None, '30687', ['SYSFT'], ''),
                         # ('800-37564-01E0', 'FTX'): (None, '53918', ['SYSFT'], ''),
                         # ('800-37564-01E0', 'FTX'): (None, '53801', ['SYSFT'], ''),
                         },

    },

    'NEWTONCR48U': {
        'cfg_pids': ['WS-C3850-48U-L', 'WS-C3850-48U-E', 'WS-C3850-48U-S'],
        'MODEL_NUM': 'WS-C3850-48U',
        'MODEL_REVISION_NUM': 'E0',
        'TAN_NUM': '800-38771-02',
        'TAN_REVISION_NUMBER': 'A0',
        'MOTHERBOARD_ASSEMBLY_NUM': '73-14983-07',
        'MOTHERBOARD_REVISION_NUM': 'A0',
        'POE1_SERIAL_NUM': '',
        'POE1_ASSEMBLY_NUM': '73-14909-02',
        'POE1_REVISION_NUM': 'B0',
        'POE2_SERIAL_NUM': '',
        'POE2_ASSEMBLY_NUM': '73-14909-02',
        'POE2_REVISION_NUM': 'B0',
        'VERSION_ID': 'V02',
        'SBC_CFG':   '17-11225-05.SBC_cfg',
        'CLEI_CODE_NUMBER': '',
        'ECI_CODE_NUMBER': '',
        'sysinit_required_to_pass': [('Doppler [0-1] PCIe link lane width is 4', 2)],
        'asic': {'core_count': 2, 'locations': ['U6', 'U7']},
        'poe': {'uut_ports': '1-48', 'type': 'UPOE', 'volt_range': (47.0, 56.0), 'current_range': (1008, 1232)},
        'diag_tests': [('PoeDetTest_CSCO',   {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [1], 'mdimode': [0, 1]}}),
                       ('PoeDetTest_IEEE_p', {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [2], 'mdimode': [1], 'poe_type': 'POE+'}}),
                       ('PoeDetTest_IEEE_u', {'cmd': 'PoeDetTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_detect_test', 'func_args': {'detecttype': [2], 'mdimode': [1], 'poe_type': 'UPOE'}}),
                       ('PoeClassTest_0',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [0]}}),
                       ('PoeClassTest_1',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [1]}}),
                       ('PoeClassTest_2',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [2]}}),
                       ('PoeClassTest_3',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [3]}}),
                       ('PoeClassTest_4',    {'cmd': 'PoeClassTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_class_test', 'func_args': {'poe_classes': [4]}}),
                       ('PoePowerTest',      {'cmd': 'PoePowerTest', 'areas': ['PCBST'], 'enabled': True, 'adt_enabled': True, 'args': '', 'func': 'diags_poe_power_test', 'func_args': {}}),
                       ],
        'traffic_cases': ('traffic_cases_library', '48'),
        'cmpd_types': ('cmpd_type_verify_manifest', ['P.48.1', 'P.48.2', 'P.48.3']),
        'eco_manifest': {('73-14983-07A0', 'ALL'): ('E118960', '61470', ['PCBST', 'PCB2C'], ''),
                         ('73-14983-06A0', 'ALL'): ('E117079', '56876', ['PCBST', 'PCB2C'], ''),
                         ('73-14983-05B0', 'ALL'): ('E115924', '54944', ['PCBST', 'PCB2C'], ''),
                         ('73-14983-0404', 'ALL'): ('E521520', '54591', ['PCBST', 'PCB2C'], ''),
                         ('73-14983-05A0', 'ALL'): ('E115090', '46651', ['PCBST', 'PCB2C'], ''),
                         ('800-38771-03D0', 'ALL'): ('EA530824', '73005', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38771-03C0', 'ALL'): ('EA527875', '70368', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38771-03B0', 'ALL'): ('EA520469', '66914', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38771-03A0', 'ALL'): ('E118960', '61487', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38771-02B0', 'ALL'): ('E119304', '59214', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38771-02A0', 'ALL'): ('E117079', '56943', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38771-01G0', 'ALL'): ('E117273', '56123', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38771-01F0', 'ALL'): ('E115956', '55027', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38771-01E0', 'ALL'): ('E115924', '54956', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38771-0137', 'ALL'): ('E521520', '54609', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38771-01C0', 'ALL'): ('E115667', '54569', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38771-01B0', 'ALL'): ('E115022', '46653', ['ASSY', 'SYSBI', 'PCBFT', 'SYSFT'], ''),
                         ('800-38771-03B0', 'FTX'): (None, '68548', ['SYSFT'], ''),
                         ('800-38771-03A0', 'FTX'): (None, '61809', ['SYSFT'], ''),
                         ('800-38771-02A0', 'FTX'): (None, '59075', ['SYSFT'], ''),
                         ('800-38771-01B0', 'FTX'): (None, '58705', ['SYSFT'], ''),
                         # ('800-38771-01B0', 'FTX'): (None, '58651', ['SYSFT'], ''),
                         # ('800-38771-02A0', 'FTX'): (None, '58416', ['SYSFT'], ''),
                         # ('800-38771-02A0', 'FTX'): (None, '58387', ['SYSFT'], ''),
                         # ('800-38771-01B0', 'FTX'): (None, '58006', ['SYSFT'], ''),
                         # ('800-38771-01B0', 'FTX'): (None, '58005', ['SYSFT'], ''),
                         # ('800-38771-01B0', 'FTX'): (None, '57857', ['SYSFT'], ''),
                         # ('800-38771-01B0', 'FTX'): (None, '57856', ['SYSFT'], ''),
                         # ('800-38771-01B0', 'FTX'): (None, '55176', ['SYSFT'], ''),
                         # ('800-38771-01B0', 'FTX'): (None, '57852', ['SYSFT'], ''),
                         ('800-38771-01G0', 'FTX'): (None, '57851', ['SYSFT'], ''),
                         # ('800-38771-01B0', 'FTX'): (None, '57674', ['SYSFT'], ''),
                         # ('800-38771-01G0', 'FTX'): (None, '57502', ['SYSFT'], ''),
                         # ('800-38771-01B0', 'FTX'): (None, '57493', ['SYSFT'], ''),
                         ('800-38771-01F0', 'FTX'): (None, '56812', ['SYSFT'], ''),
                         ('800-38771-03D0', 'FTX'): (None, '73461', ['SYSFT'], ''),
                         ('800-38771-03C0', 'FTX'): (None, '70810', ['SYSFT'], ''),
                         },

    },


}  # family_end
